/**
 * Generated artifact text: the WSL-side start/stop scripts and the hidden
 * Windows launcher. The tray helper itself lives in tray-script.ts; the names
 * and launch facts are re-exported from names.ts so existing importers keep
 * working.
 */
export * from "./names.js";
export { buildTrayScript, wslLogUncPath } from "./tray-script.js";
import { PLUGIN_ID, TRAY_SCRIPT_NAME, WSL_DIR_NAME } from "./names.js";
/**
 * Quote a value for bash. JSON escaping is NOT shell escaping: inside double
 * quotes bash still expands `$(...)`, backticks and `$VAR`, and it turns a
 * newline into the two characters `\` and `n` — so a path containing either was
 * executed or corrupted. Single quotes with `'\''` doubling keep every byte and
 * expand nothing.
 *
 * The PowerShell counterpart is `psSingleQuoted` in tray-script.ts.
 *
 * @param value - the literal to quote.
 */
export function bashSingleQuoted(value) {
    return `'${value.replace(/'/g, "'\\''")}'`;
}
/**
 * Build the WSL-side launcher. It starts the same DSH web CLI the running
 * plugin host came from, waits for readiness, and opens the default browser.
 *
 * Source checkouts are launched through their BUILD OUTPUT only. Running one
 * from `src` (tsx) puts a src instance and a lib instance of the same packages
 * in one process — plugin packages resolve through the runtime mode, which
 * loads lib — and symbols never cross instances, so tool calls fail with
 * undefined state. When a project path is configured explicitly, a missing
 * build output is a hard error rather than a silent fallback to another
 * install the user did not ask for.
 *
 * @param params - launch facts resolved from the running host.
 */
export function buildStartScript(params) {
    const logFile = `"$HOME/.dsh/${WSL_DIR_NAME}/start.log"`;
    const sourceCli = bashSingleQuoted(params.sourceCli ?? '');
    const sourceCwd = bashSingleQuoted(params.sourceCwd ?? '');
    const bakedCli = bashSingleQuoted(params.bakedCli ?? '');
    const sourceConfigured = params.sourceConfigured === true ? '1' : '0';
    return `#!/usr/bin/env bash
# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
set -u

URL=${bashSingleQuoted(params.webUrl)}
LOG_FILE=${logFile}
PID_FILE="$HOME/.dsh/${WSL_DIR_NAME}/dsh.pid"
NODE=${bashSingleQuoted(params.nodeBin)}
SOURCE_CLI=${sourceCli}
SOURCE_CWD=${sourceCwd}
SOURCE_CONFIGURED=${sourceConfigured}
BAKED_CLI=${bakedCli}

# Forward machine-local secrets to the launched DSH (e.g. GITHUB_TOKEN for an MCP
# server that needs one). One KEY=VALUE per line, chmod 600 — this script only
# reads the file, it never creates it. The github-mcp-token name is the older,
# personal one and is still honoured so existing installs keep working.
for env_file in "$HOME/.dsh/${WSL_DIR_NAME}.env" "$HOME/.dsh/github-mcp-token"; do
  [ -f "$env_file" ] || continue
  set -a
  . "$env_file"
  set +a
done

# Liveness probe with a dependency chain: curl, then wget, then bash's own
# /dev/tcp so a minimal distro without downloaders still detects a live DSH.
is_ready() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsS -o /dev/null --max-time 2 "$URL" 2>/dev/null
  elif command -v wget >/dev/null 2>&1; then
    wget -q -T 2 -O /dev/null "$URL" 2>/dev/null
  else
    local host port
    host=\${URL#http://}; host=\${host%%/*}
    port=\${host##*:}; host=\${host%%:*}
    (exec 3<>"/dev/tcp/$host/$port") 2>/dev/null
  fi
}

mkdir -p "$(dirname "$LOG_FILE")"

log() {
  printf '%s %s\\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >>"$LOG_FILE"
}

if is_ready; then
  exit 0
fi

# A source checkout is always launched through its BUILD OUTPUT
# (apps/cli/lib/bin.js). Launching one from src mixes a src instance and a lib
# instance of the same packages in one process — plugin packages resolve
# through the runtime resolution mode, which loads lib — and symbols never
# cross instances, so tool state comes back undefined and tool calls fail.
# This script therefore never launches src.
source_build_ready() {
  [ -n "$SOURCE_CLI" ] && [ -f "$SOURCE_CLI" ]
}

# Freshness check, run once per launch: a stale build output runs old code,
# which looks exactly like a code change that did nothing. The fix is printed,
# because this script cannot rebuild the checkout on its own.
source_build_stale() {
  local src_dir newer
  [ -n "$SOURCE_CLI" ] || return 1
  src_dir="$(dirname "$(dirname "$SOURCE_CLI")")/src"
  [ -d "$src_dir" ] || return 1
  newer="$(find "$src_dir" -name '*.ts' -newer "$SOURCE_CLI" -print -quit 2>/dev/null)"
  [ -n "$newer" ]
}

# Run the checkout's build output in the FOREGROUND of the hidden wsl.exe
# session so WSL keeps the distro alive and this PID tracks the final process.
start_from_source_build() {
  if source_build_stale; then
    log "WARN cli sources are newer than the build output; run 'pnpm run build' to refresh $SOURCE_CLI"
  fi
  if [ -n "$SOURCE_CWD" ] && [ -d "$SOURCE_CWD" ]; then
    cd "$SOURCE_CWD" 2>/dev/null || true
  fi
  log "launching DSH from the source build output: $SOURCE_CLI"
  exec "$NODE" "$SOURCE_CLI" web --no-open >>"$LOG_FILE" 2>&1
}

# Launch DSH hidden and in the foreground. Try the most reliable launcher
# first, then the baked-in current CLI, then npx, so npm / npx installs all
# work; a configured source checkout takes precedence over all of them.
launch_dsh() {
  # exec keeps the shell PID, so this file tracks the final DSH process and
  # stop.sh can stop exactly the instance this script launched.
  echo $$ > "$PID_FILE"

  # An explicitly configured project path means "run this checkout": only its
  # build output is acceptable — never src (see above), and never whichever
  # dsh happens to be on PATH, which may be a different version entirely.
  if [ "$SOURCE_CONFIGURED" = "1" ]; then
    if source_build_ready; then
      start_from_source_build
    fi
    log "ERROR source build output is missing: $SOURCE_CLI"
    log "ERROR build the checkout before launching it: cd \${SOURCE_CWD:-CHECKOUT_ROOT} && pnpm run build"
    exit 1
  fi

  if command -v dsh >/dev/null 2>&1; then
    exec dsh web --no-open >>"$LOG_FILE" 2>&1
  fi

  if source_build_ready; then
    start_from_source_build
  fi

  if [ -n "$BAKED_CLI" ] && [ -x "$BAKED_CLI" ]; then
    exec "$NODE" "$BAKED_CLI" web --no-open >>"$LOG_FILE" 2>&1
  fi

  if command -v npx >/dev/null 2>&1; then
    exec npx --yes dsh web --no-open >>"$LOG_FILE" 2>&1
  fi

  log "ERROR no usable DSH launcher found (no dsh on PATH, no source build output, no npx)"
  echo "No usable DSH launcher found. Check $LOG_FILE" >&2
  exit 1
}

launch_dsh
`;
}
/**
 * Build the WSL-side stop script. It is what the tray's exit entry runs: the
 * generated script stops exactly the instance start.sh launched (PID file,
 * written before exec so it tracks the final DSH process), then falls back to
 * every other `dsh web` process on the machine.
 *
 * The fallback enumerates candidates with pgrep and applies the same predicate
 * the PID file gets — a global install's own command line is
 * `node /usr/local/bin/dsh web` (the shim keeps the symlink path in argv), which
 * none of the `bin.js web` patterns match, and a `grep dsh web` of your own is
 * never signalled because the predicate inspects /proc, not the pattern text.
 *
 * The PID from the file is checked against /proc before anything is signalled: a
 * stale PID file plus a reused PID would otherwise kill an unrelated process.
 * That is the same idea as the port-verified kill a Tauri tray app uses on
 * Windows (resolve the owner, check what it actually is, then terminate).
 */
export function buildStopScript() {
    return `#!/usr/bin/env bash
# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
set -u

PID_FILE="$HOME/.dsh/${WSL_DIR_NAME}/dsh.pid"

# Whether a PID is really a DSH web process. A reused PID is not ours to kill.
is_dsh_web() {
  local cmdline
  [ -r "/proc/$1/cmdline" ] || return 1
  cmdline="$(tr '\\0' ' ' < "/proc/$1/cmdline" 2>/dev/null)"
  case "$cmdline" in
    *"bin.js web"*|*"src/bin.ts web"*|*"dsh web"*) return 0 ;;
  esac
  return 1
}

if [ -r "$PID_FILE" ]; then
  pid="$(cat "$PID_FILE" 2>/dev/null || true)"
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    if is_dsh_web "$pid"; then
      kill "$pid" 2>/dev/null || true
    else
      echo "stop.sh: PID $pid from the PID file is not a DSH web process; leaving it alone" >&2
    fi
  fi
  rm -f "$PID_FILE"
fi

# Instances this script did not launch: no PID file, or a stale one. Each
# candidate is checked with the same predicate the PID file uses, so a
# hand-started node /usr/local/bin/dsh web (what a global install looks like on
# this machine) is stopped, and the pgrep pattern itself is never signalled.
if command -v pgrep >/dev/null 2>&1; then
  for pid in $(pgrep -f '[d]sh web' 2>/dev/null || true); do
    [ "$pid" = "$$" ] && continue
    if is_dsh_web "$pid"; then
      kill "$pid" 2>/dev/null || true
    fi
  done
else
  # No procps: bracket the first character so the pattern does not match itself.
  pkill -f '[b]in\\.js web' 2>/dev/null || true
  pkill -f '[s]rc/bin\\.ts web' 2>/dev/null || true
  pkill -f '[d]sh web' 2>/dev/null || true
fi
exit 0
`;
}
/**
 * Build the Windows-side hidden launcher for the tray helper.
 *
 * The shortcut runs `wscript.exe //E:JScript //B <this file>`. `wscript.exe` is
 * a GUI-subsystem host, so no console is ever allocated and the tray appears
 * without a window; the explicit `//E:JScript` names the engine instead of
 * letting Windows derive it from the file extension.
 *
 * Upstream started a `.vbs` without `//E:`, and that is a real failure mode
 * now: Windows 11 24H2 ships VBScript as a Feature-on-Demand, and a machine can
 * end up with `HKCR\.vbs` carrying no ProgID while `vbscript.dll` is still
 * registered. Windows Script Host then refuses to run the file at all
 * (没有文件扩展'.vbs'的脚本引擎), the tray never starts, and double-clicking
 * the shortcut looks like nothing happening. JScript is not part of the
 * VBScript deprecation, and `//E:` keeps working even when the extension
 * mapping is gone — `wscript.exe //E:JScript file.txt` runs like `file.js`.
 */
export function buildLauncherScript() {
    return `// Generated by ${PLUGIN_ID}. Do not edit by hand.
// Started by the desktop shortcut as:
//   wscript.exe //E:JScript //B "<this file>"
// wscript.exe keeps the console away; //E:JScript names the script engine, so
// a machine whose .js/.vbs file association is missing or broken (VBScript is
// a Feature-on-Demand since Windows 11 24H2) still starts the tray.
var fso = new ActiveXObject('Scripting.FileSystemObject');
var dir = fso.GetParentFolderName(WScript.ScriptFullName);
// Absolute PowerShell: a bare name depends on PATH. Fall back to the name when
// the expected location is absent.
var powershell = fso.BuildPath(fso.GetSpecialFolder(1).Path, 'WindowsPowerShell\\\\v1.0\\\\powershell.exe');
if (!fso.FileExists(powershell)) { powershell = 'powershell.exe'; }
var tray = fso.BuildPath(dir, '${TRAY_SCRIPT_NAME}');
var shell = new ActiveXObject('WScript.Shell');
// Window style 0 and no wait: the tray helper runs hidden and this launcher
// returns immediately, so a second double-click only hits the tray's mutex.
shell.Run('"' + powershell + '" -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "' + tray + '"', 0, false);
`;
}
