/**
 * The generated Windows-side tray helper.
 *
 * This is the one process deliberately independent of DSH: it opens DSH when it
 * is asked to and disappears when the user exits it. It is a launcher, not a
 * supervisor — no watchdog, no idle stop, no configuration file — because all
 * of that needed background sampling and a state machine on the UI thread, and
 * the synchronous `wsl.exe` stop it offered is exactly what used to freeze the
 * tray solid (it never exited, and the menu stopped responding).
 *
 * The context menu is styled after the DeepSeek Harness desktop app's own tray
 * menu. That menu is NOT a Windows menu: Electron hands a template to Chromium
 * and Chromium draws it, so its palette and metrics differ from the Windows 11
 * popup menu. Both were measured side by side on the same screen and at the
 * same DPI (tray icon vs tray icon), and those numbers are the constants below.
 *
 * The generated script is deliberately plain PowerShell 5.1: no modules, just
 * WinForms, plus one `Add-Type` for the dark context menu.
 */
import { ICON_FILE_NAME, LAUNCHER_SCRIPT_NAME, PLUGIN_ID, TRAY_ICON_FILE_NAME, TRAY_LOG_NAME, TRAY_SCRIPT_NAME, } from "./names.js";
/** Single-instance mutex name; one tray per user session. */
function mutexName() {
    return `Local\\${PLUGIN_ID}-single`;
}
/**
 * Escape a value baked into a PowerShell single-quoted string. JSON escaping is
 * NOT PowerShell escaping: a double-quoted PS string interpolates `$` and
 * treats `"` as a terminator, so baked values use single quotes with the `''`
 * doubling rule.
 */
function psSingleQuoted(value) {
    return `'${value.replace(/'/g, "''")}'`;
}
/** `\\wsl.localhost\<distro>\home\me\.dsh\dsh-web-tray\start.log` from a WSL path. */
export function wslLogUncPath(distro, wslLogPath) {
    const relative = wslLogPath.replace(/^\/+/, '').replace(/\//g, '\\');
    return `\\\\wsl.localhost\\${distro}\\${relative}`;
}
/**
 * Build the Windows tray helper: a notification-area icon whose context menu
 * offers exactly two actions, 打开 and 退出.
 *
 * Opening is idempotent — a running DSH is reused and only the browser opens,
 * a stopped one is started through the generated `start.sh` and the browser
 * opens once the URL answers. Nothing is sampled in the background, so the UI
 * thread never blocks on WSL and the tray cannot wedge.
 *
 * `-Regenerate` (used by the host on mount and by the settings card) only
 * rewrites the desktop shortcut; `-SelfTest` builds the real menu and prints the
 * contract as JSON without showing any UI; `-Uninstall` deletes everything this
 * helper writes (the plugin itself cannot: removing a bundle runs no code).
 *
 * @param config - launch facts baked into the script.
 */
export function buildTrayScript(config) {
    const distro = psSingleQuoted(config.distro);
    const webUrl = psSingleQuoted(config.webUrl);
    const shortcutName = psSingleQuoted(config.shortcutName);
    const wslStartScript = psSingleQuoted(config.wslStartScript);
    const wslStopScript = psSingleQuoted(config.wslStopScript);
    const wslStartLogUnc = psSingleQuoted(wslLogUncPath(config.distro, config.wslStartLogPath));
    return `# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
param(
  [switch]$Regenerate,
  [switch]$SelfTest,
  [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$distro = ${distro}
$webUrl = ${webUrl}
$shortcutName = ${shortcutName}
$wslStartScript = ${wslStartScript}
$wslStopScript = ${wslStopScript}
$wslStartLogUnc = ${wslStartLogUnc}

# Menu labels, in the desktop app's wording and order.
$openLabel = '打开 DeepSeek Harness'
$exitLabel = '退出 DeepSeek Harness'
# How long a started DSH gets to answer before the tray gives up opening a page.
$openTimeoutSec = 120
$probeTimeoutSec = 2
# Menu metrics in 96-DPI pixels, measured from the desktop app's own tray menu
# on the same screen (see the comments above the colour table below). The corner
# radius is not here: Windows 11 rounds the popup itself.
$panelPaddingPx = 12
$itemHeightPx = 28
$itemTextInsetPx = 20
$separatorGapPx = 17
# The app's labels sit about a pixel below the middle of their 28 px box (measured:
# its ink centroid is 1.2 px below the box centre, ours was 0.2 px), which is the
# whole of the spare space its menu has under the last line: 18 px there against
# 19-20 px here. Its separator box is 17 px rather than 18 as well, so its panel is
# 175x97 where ours was 175x98.
$itemTextDropPx = 1

$scriptDir = Split-Path -Parent $PSCommandPath
$iconPath = Join-Path $scriptDir '${ICON_FILE_NAME}'
$trayIconPath = Join-Path $scriptDir '${TRAY_ICON_FILE_NAME}'
$launcherPath = Join-Path $scriptDir '${LAUNCHER_SCRIPT_NAME}'
$trayLogPath = Join-Path $scriptDir '${TRAY_LOG_NAME}'

# ---- log ----
# One line per event; the tray writes a handful per run, so there is no
# rotation to maintain.
function Write-TrayLog([string]$Level, [string]$Message) {
  try {
    Add-Content -Path $trayLogPath -Value ('{0} | {1,-5} | {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Level, $Message) -Encoding UTF8
  } catch {}
}

# ---- shortcut ----
# A script engine has to be named explicitly. Windows 11 24H2 ships VBScript as
# a Feature-on-Demand, and a machine can end up with no engine mapped to .vbs at
# all; a shortcut that then runs a bare .vbs dies with the script-host error
# (没有文件扩展'.vbs'的脚本引擎) and the tray never starts. JScript is not part of
# that deprecation and //E: bypasses the extension mapping, so it is the first
# choice; PowerShell is the fallback for a host without JScript (it can show a
# terminal window when Windows Terminal is the default console host, which is
# why it is not the first choice).
function Test-ScriptEngine([string]$name) {
  try {
    $clsid = (Get-ItemProperty -LiteralPath ('HKLM:\\SOFTWARE\\Classes\\' + $name + '\\CLSID') -ErrorAction Stop).'(default)'
    if (-not $clsid) { return $false }
    $dll = (Get-ItemProperty -LiteralPath ('HKLM:\\SOFTWARE\\Classes\\CLSID\\' + $clsid + '\\InprocServer32') -ErrorAction Stop).'(default)'
    if (-not $dll) { return $false }
    return (Test-Path -LiteralPath ([Environment]::ExpandEnvironmentVariables($dll)))
  } catch {
    return $false
  }
}

function Get-ShortcutTarget {
  $system = [Environment]::SystemDirectory
  if (Test-ScriptEngine 'JScript') {
    return [pscustomobject]@{
      Path = (Join-Path $system 'wscript.exe')
      Arguments = '//E:JScript //B "' + $launcherPath + '"'
    }
  }
  return [pscustomobject]@{
    Path = (Join-Path $system 'WindowsPowerShell\\v1.0\\powershell.exe')
    Arguments = '-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "' + (Join-Path $scriptDir '${TRAY_SCRIPT_NAME}') + '"'
  }
}

# Explorer caches a shortcut's icon by path, so a restyled .ico keeps showing the
# old art — a stale icon is what made the shortcut look wrong after a regenerate.
# SHCNE_ASSOCCHANGED + SHCNF_FLUSH is the documented way to drop that cache.
function Update-ShellIconCache {
  try {
    if (-not ('DshWebTray.Shell32' -as [type])) {
      Add-Type -Namespace DshWebTray -Name Shell32 -MemberDefinition @'
[DllImport("shell32.dll", CharSet=CharSet.Auto)]
public static extern void SHChangeNotify(int eventId, uint flags, System.IntPtr item1, System.IntPtr item2);
'@
    }
    [DshWebTray.Shell32]::SHChangeNotify(0x08000000, 0x1000, [System.IntPtr]::Zero, [System.IntPtr]::Zero)
  } catch {
    Write-TrayLog 'WARN' ('could not refresh the shell icon cache: {0}' -f $_.Exception.Message)
  }
}

function New-DshShortcut {
  $desktop = [Environment]::GetFolderPath('Desktop')
  $lnkPath = Join-Path $desktop ($shortcutName + '.lnk')
  $shell = New-Object -ComObject WScript.Shell
  $shortcut = $shell.CreateShortcut($lnkPath)
  $target = Get-ShortcutTarget
  $shortcut.TargetPath = $target.Path
  $shortcut.Arguments = $target.Arguments
  $shortcut.WorkingDirectory = $scriptDir
  $shortcut.IconLocation = $iconPath + ',0'
  $shortcut.Description = $shortcutName + ' (WSL)'
  $shortcut.Save()
  Write-TrayLog 'INFO' ('desktop shortcut written: {0} -> {1} {2}' -f $lnkPath, $target.Path, $target.Arguments)
  Update-ShellIconCache
}

# Undo everything this helper writes. The plugin has no uninstall hook -- removing
# the bundle cannot run any code -- so this is the cleanup path: it works whether it
# is run before or after "dsh plugin remove", and running it twice is harmless.
# DSH itself is left running; stop it first from the menu if that is the intent.
function Remove-DshArtifacts {
  $removed = New-Object System.Collections.Generic.List[string]

  # Any tray running from this directory (this process is not one of them: it is a
  # fresh -Uninstall invocation).
  foreach ($process in @(Get-CimInstance Win32_Process -Filter "Name = 'powershell.exe'" -ErrorAction SilentlyContinue)) {
    if ($process.ProcessId -eq $PID) { continue }
    if ($process.CommandLine -and $process.CommandLine.Contains($PSCommandPath)) {
      Stop-Process -Id $process.ProcessId -Force -ErrorAction SilentlyContinue
      $removed.Add('tray process ' + $process.ProcessId)
    }
  }

  # The desktop shortcut, and the shell's cached icon for it.
  $lnkPath = Join-Path ([Environment]::GetFolderPath('Desktop')) ($shortcutName + '.lnk')
  if (Test-Path -LiteralPath $lnkPath) {
    Remove-Item -LiteralPath $lnkPath -Force -ErrorAction SilentlyContinue
    Update-ShellIconCache
    $removed.Add($lnkPath)
  }

  # The generated files next to this script (this one included: PowerShell reads a
  # script in full before running it, so deleting it here is safe), then the
  # directory itself if that leaves it empty.
  $selftestPath = Join-Path $scriptDir 'tray-selftest.json'
  foreach ($file in @($PSCommandPath, $launcherPath, $iconPath, $trayIconPath, $trayLogPath, $selftestPath)) {
    if (Test-Path -LiteralPath $file) {
      Remove-Item -LiteralPath $file -Force -ErrorAction SilentlyContinue
      $removed.Add($file)
    }
  }
  Remove-Item -LiteralPath $scriptDir -Force -ErrorAction SilentlyContinue

  # The WSL side: start.sh, stop.sh, start.log, dsh.pid, project-path.json.
  $wslDir = $wslStartScript -replace '/[^/]+$', ''
  try {
    & wsl.exe -d $distro -- bash -lc ('rm -rf ' + $wslDir)
    $removed.Add($wslDir + ' (inside ' + $distro + ')')
  } catch {
    Write-Output ('could not remove ' + $wslDir + ' inside ' + $distro + ': ' + $_.Exception.Message)
  }

  Write-Output ('dsh-web-tray removed ' + $removed.Count + ' item(s): ' + ($removed -join '; '))
  Write-Output 'DSH itself was left running; remove the bundle with: dsh plugin remove dsh-web-tray'
}

if ($Uninstall) {
  Remove-DshArtifacts
  return
}

if ($Regenerate) {
  New-DshShortcut
  Write-Output (Join-Path ([Environment]::GetFolderPath('Desktop')) ($shortcutName + '.lnk'))
  return
}

# ---- opening DSH ----
$shell = New-Object -ComObject WScript.Shell

# The page's own title, and the process name that must never be touched: the Electron
# desktop app is a different program with its own backend, and this plugin has nothing
# to do with it — its window happens to carry the same words in its title, so it is
# excluded by name.
$dshPageTitleNeedle = 'DeepSeek Harness'
$dshAppProcessName = 'DeepSeek Harness.exe'
# Chromium (and Edge, Brave, ...) draw every window with this class, including an
# installed web app's own window. Requiring it keeps titles from other programs out.
$dshWindowClass = 'Chrome_WidgetWin_1'

function Find-DshWindow {
  # A window that already shows the DSH page: an installed web app window (a browser
  # started with --app / --app-id) when there is one, otherwise a browser window whose
  # active tab is DSH. Returns a hashtable so the caller can say which it was.
  $none = @{ Handle = [IntPtr]::Zero; WebApp = $false; Description = ''; SkippedApp = 0 }
  try {
    $candidates = @([DshTrayTarget]::FindTitledWindows($dshPageTitleNeedle, $dshWindowClass))
    if ($candidates.Count -eq 0) { return $none }
    $fallback = $null
    foreach ($handle in $candidates) {
      $process = Get-CimInstance Win32_Process -Filter ('ProcessId = ' + [DshTrayTarget]::OwnerOf($handle)) -ErrorAction SilentlyContinue
      if ($process -eq $null) { continue }
      if ($process.Name -eq $dshAppProcessName) { $none.SkippedApp = $none.SkippedApp + 1; continue }
      $entry = @{ Handle = $handle; WebApp = ($process.CommandLine -match '--app(-id)?='); Description = [DshTrayTarget]::Describe($handle); SkippedApp = $none.SkippedApp }
      if ($entry.WebApp) { return $entry }
      if ($fallback -eq $null) { $fallback = $entry }
    }
    if ($fallback -ne $null) { $fallback.SkippedApp = $none.SkippedApp; return $fallback }
    $none.SkippedApp = $none.SkippedApp
    return $none
  } catch { return $none }
}

function Open-DshSurface {
  # Reuse first: a window already showing the page, so no second tab and no new WSL
  # instance just to display something. Returning $true means it was brought forward.
  $found = Find-DshWindow
  if ($found.Handle -ne [IntPtr]::Zero) {
    if ([DshTrayTarget]::Focus($found.Handle)) {
      Write-TrayLog 'INFO' ('brought the DSH window forward ({0}): {1}' -f $(if ($found.WebApp) { 'installed web app' } else { 'browser' }), $found.Description)
      # The window is only worth having if the instance behind it is up: a page left on
      # an error page would otherwise stay broken. The probe is a local request, so it
      # costs milliseconds while DSH answers (a 401 counts as alive).
      if (-not (Test-DshAlive)) {
        Start-DshWsl
        $script:opening = $true
        $script:openDeadline = (Get-Date).AddSeconds($openTimeoutSec)
        if ($script:openTimer -ne $null) { $script:openTimer.Start() }
        Write-TrayLog 'INFO' ('{0} was not answering behind that window; started DSH through {1}' -f $webUrl, $wslStartScript)
      }
      return $true
    }
    Write-TrayLog 'WARN' ('found the DSH window but Windows refused the foreground: {0}' -f $found.Description)
  }
  return $false
}

function Start-DshWsl {
  # Hidden, non-blocking: WScript.Shell.Run with window style 0 starts no console
  # window, and bWaitOnReturn = $false keeps the UI thread free.
  $wslCmd = 'wsl.exe -d ' + $distro + ' -- bash -lc "' + $wslStartScript + '"'
  $shell.Run($wslCmd, 0, $false) | Out-Null
}

# The reverse, for the menu's exit entry: the generated stop script stops exactly
# the instance start.sh launched. Hidden and NOT awaited — the old menu item that
# stopped DSH waited for wsl.exe on the UI thread, and one call that never
# returned left the tray frozen forever.
function Stop-Dsh {
  try {
    $wslCmd = 'wsl.exe -d ' + $distro + ' -- bash -lc "' + $wslStopScript + '"'
    $shell.Run($wslCmd, 0, $false) | Out-Null
    Write-TrayLog 'INFO' ('DSH stop requested through {0} (hidden, not awaited)' -f $wslStopScript)
  } catch {
    Write-TrayLog 'WARN' ('could not ask WSL to stop DSH: {0}' -f $_.Exception.Message)
  }
}

# Whether the web URL answers. A 401 still means the server is up: without a
# cookie DSH answers 401 by design, and the browser is opened with the token URL
# from the start script's log.
function Test-DshAlive {
  try {
    $response = Invoke-WebRequest -Uri $webUrl -UseBasicParsing -TimeoutSec $probeTimeoutSec
    return ($response.StatusCode -ge 200 -and $response.StatusCode -lt 500)
  } catch {
    $status = 0
    try { if ($_.Exception.Response -ne $null) { $status = [int]$_.Exception.Response.StatusCode } } catch {}
    return ($status -ge 200 -and $status -lt 500)
  }
}

# The launch token belongs to one DSH process and is printed once per run into
# the start script's log; reading it from the Windows side avoids a wsl.exe
# round-trip. Without it the browser would land on a 401 page.
function Get-WebAuthUrl {
  try {
    if (-not (Test-Path -LiteralPath $wslStartLogUnc)) { return $null }
    $tail = @(Get-Content -LiteralPath $wslStartLogUnc -Tail 120 -Encoding UTF8 -ErrorAction Stop)
    for ($i = $tail.Count - 1; $i -ge 0; $i--) {
      if ($tail[$i] -match 'http://127\\.0\\.0\\.1:\\d+/\\?token=[A-Za-z0-9_-]+') { return $Matches[0] }
    }
  } catch {}
  return $null
}

function Open-DshPage {
  # A double click is two clicks, and a second browser tab is not what the user
  # meant by it.
  if (((Get-Date) - $script:lastOpenAt).TotalMilliseconds -lt 800) { return }
  $script:lastOpenAt = Get-Date
  $auth = Get-WebAuthUrl
  $target = $webUrl
  if ($auth -ne $null) { $target = $auth }
  try {
    Start-Process $target
    Write-TrayLog 'INFO' ('opened {0}' -f $target)
  } catch {
    Write-TrayLog 'WARN' ('could not open {0}: {1}' -f $target, $_.Exception.Message)
  }
}

# Ask DSH to show itself: reuse a running instance at once, otherwise start it
# and let the timer open the page as soon as the URL answers.
$script:lastOpenAt = [DateTime]::MinValue
$script:openTimer = $null
$script:openDeadline = $null
$script:opening = $false

function Start-OpenFlow {
  if ($script:opening) { return }
  if (Open-DshSurface) { return }
  if (Test-DshAlive) {
    Open-DshPage
    return
  }
  $script:opening = $true
  Start-DshWsl
  $script:openDeadline = (Get-Date).AddSeconds($openTimeoutSec)
  Write-TrayLog 'INFO' ('{0} is not answering; started DSH through {1}' -f $webUrl, $wslStartScript)
  if ($script:openTimer -ne $null) { $script:openTimer.Start() }
}

# Blocking variant for the second instance: it has no tray and no message pump,
# so a plain wait loop is the whole job.
function Invoke-OpenFlowAndWait {
  if (Open-DshSurface) { return }
  if (Test-DshAlive) {
    Open-DshPage
    return
  }
  Start-DshWsl
  $deadline = (Get-Date).AddSeconds($openTimeoutSec)
  while ((Get-Date) -lt $deadline) {
    Start-Sleep -Seconds 2
    if (Test-DshAlive) {
      Open-DshPage
      return
    }
  }
  Write-TrayLog 'WARN' ('gave up waiting for {0} after {1}s' -f $webUrl, $openTimeoutSec)
}

# ---- the tray menu ----
# Measured side by side on this machine's screen, the official DeepSeek Harness
# tray icon next to this one, both at 100% DPI:
#
#                        desktop app (Chromium)         Windows 11 popup menu
#   panel                175 x 97 px, #1F1F1F           224 x 66 px, #2C2C2C
#   item height          28 px                          33 px
#   text inset           20 px                          18 px
#   panel padding        12 px top/bottom               ~3 px
#   separator            #5E5E5E, full panel width      #3E3E3E
#   hovered item         #363636, full panel width      system colour
#   corner radius        12 px, anti-aliased            system
#   item text            #E3E3E3, hovered as well       #FFFFFF
#   font                 system UI, 9pt (YaHei UI)     Microsoft YaHei UI 12pt
#
# So the app's menu is not a Windows menu at all (Electron hands a template to
# Chromium, which draws it), and asking Windows for a menu cannot reproduce it.
# WinForms has no dark mode either, so the panel is composed from a professional
# colour table plus the numbers above — the same approach the desktop app's
# renderer takes. The corners are the one measurement this gives up: they come
# from Windows, which rounds a popup by 8 px rather than 12, and in exchange the
# edges are anti-aliased and the shadow is the real one.
$menuStyleSource = @'
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Text;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;

/** Process setup that must happen before the first window exists. */
public static class DshTraySetup {
  [DllImport("user32.dll")] private static extern bool SetProcessDPIAware();
  [DllImport("kernel32.dll")] private static extern bool FreeConsole();

  /**
   * DPI awareness and visual styles. Both have to be set before any window is
   * created, and both change what the menu looks like: without DPI awareness
   * Windows bitmap-scales the panel, and without visual styles the professional
   * renderer falls back to SYSTEM colours — the hovered item then comes out
   * accent blue (0x0078D7) instead of the app's #363636.
   */
  public static void Enable() {
    try { SetProcessDPIAware(); } catch { }
    try { Application.EnableVisualStyles(); } catch { }
  }

  /**
   * Drop the console this process inherited from its hidden launcher.
   *
   * The tray is a GUI and needs no console, yet a console-hosted PowerShell keeps
   * one (measured: a hidden ConsoleWindowClass window in the tray process). Windows
   * names an unowned top-level window after its process, so that console is what
   * puts "Windows PowerShell" in the taskbar while the menu is open, and showing or
   * restoring it is what pops a PowerShell window up. Tray mode therefore owns no
   * console at all; the command-line flags keep theirs for their output.
   */
  public static void DetachConsole() {
    try { FreeConsole(); } catch { }
  }
}

/** Window styles the tray menu needs, so it is never taken for an app window. */
public static class DshTrayWindow {
  private const int ExStyle = -20;
  private const long WsExToolWindow = 0x00000080L;
  private const long WsExAppWindow = 0x00040000L;
  [DllImport("user32.dll", EntryPoint = "GetWindowLongPtrW")] private static extern IntPtr GetWindowLongPtr(IntPtr hwnd, int index);
  [DllImport("user32.dll", EntryPoint = "SetWindowLongPtrW")] private static extern IntPtr SetWindowLongPtr(IntPtr hwnd, int index, IntPtr value);

  /** Current extended window style, reported by the self-test contract. */
  public static long ExStyleOf(IntPtr hwnd) {
    try { return GetWindowLongPtr(hwnd, ExStyle).ToInt64(); } catch { return 0; }
  }

  /**
   * Make the popup a tool window: no taskbar button, no Alt-Tab entry.
   *
   * WinForms leaves a ContextMenuStrip shown on its own as an ordinary unowned
   * top-level window (measured: exstyle 0x00010008, no WS_EX_TOOLWINDOW, owner
   * none), and Explorer labels such a window after its process — whose window title
   * comes from the console. Applying this before the first show is what keeps the
   * menu from being listed as "Windows PowerShell".
   */
  public static void MarkToolWindow(IntPtr hwnd) {
    try {
      long style = GetWindowLongPtr(hwnd, ExStyle).ToInt64();
      long wanted = (style | WsExToolWindow) & ~WsExAppWindow;
      if (wanted != style) { SetWindowLongPtr(hwnd, ExStyle, new IntPtr(wanted)); }
    } catch { }
  }
}

/**
 * Finding and bringing forward the DSH page's own window: an installed web app
 * window if the browser has one, otherwise a browser window whose active tab is DSH.
 * The Electron desktop app is deliberately not a candidate — this plugin only ever
 * deals with the WSL web instance, and the caller excludes that process by name.
 */
public static class DshTrayTarget {
  public delegate bool EnumProc(IntPtr hwnd, IntPtr param);
  [StructLayout(LayoutKind.Sequential)] private struct RECT { public int Left, Top, Right, Bottom; }
  [StructLayout(LayoutKind.Sequential)] private struct POINT { public int X; public int Y; }
  [StructLayout(LayoutKind.Sequential)] private struct WINDOWPLACEMENT {
    public int length;
    public int flags;
    public int showCmd;
    public POINT minPosition;
    public POINT maxPosition;
    public RECT normalPosition;
  }
  private const uint GwOwner = 4;
  private const int SwRestore = 9;
  private const int ShowMinimized = 2;
  private const byte VkMenu = 0x12; // ALT

  [DllImport("user32.dll")] private static extern bool EnumWindows(EnumProc callback, IntPtr param);
  [DllImport("user32.dll")] private static extern bool IsWindowVisible(IntPtr hwnd);
  [DllImport("user32.dll")] private static extern bool IsIconic(IntPtr hwnd);
  [DllImport("user32.dll")] private static extern bool GetWindowRect(IntPtr hwnd, out RECT rect);
  [DllImport("user32.dll")] private static extern bool GetWindowPlacement(IntPtr hwnd, ref WINDOWPLACEMENT placement);
  [DllImport("user32.dll")] private static extern IntPtr GetWindow(IntPtr hwnd, uint command);
  [DllImport("user32.dll")] private static extern IntPtr GetForegroundWindow();
  [DllImport("user32.dll")] private static extern bool ShowWindow(IntPtr hwnd, int command);
  [DllImport("user32.dll")] private static extern bool SetForegroundWindow(IntPtr hwnd);
  [DllImport("user32.dll")] private static extern bool BringWindowToTop(IntPtr hwnd);
  [DllImport("user32.dll")] private static extern bool AttachThreadInput(uint attach, uint attachTo, bool flag);
  [DllImport("user32.dll")] private static extern void keybd_event(byte key, byte scan, uint flags, UIntPtr extra);
  [DllImport("user32.dll")] private static extern uint GetWindowThreadProcessId(IntPtr hwnd, out uint processId);
  [DllImport("user32.dll", CharSet = CharSet.Unicode)] private static extern int GetWindowTextW(IntPtr hwnd, StringBuilder text, int max);
  [DllImport("user32.dll", CharSet = CharSet.Unicode)] private static extern int GetClassNameW(IntPtr hwnd, StringBuilder text, int max);

  /**
   * The size a window restores to, and its show state (1 normal, 2 minimized,
   * 3 maximized). GetWindowRect is useless for a minimized window — it reports a
   * 160x28 placeholder for the desktop app while it sits in the taskbar — and that
   * is exactly the window the tray has to recognise.
   */
  private static bool Placement(IntPtr hwnd, out int width, out int height, out int showCmd) {
    width = 0; height = 0; showCmd = 0;
    try {
      WINDOWPLACEMENT placement = new WINDOWPLACEMENT();
      placement.length = Marshal.SizeOf(typeof(WINDOWPLACEMENT));
      if (!GetWindowPlacement(hwnd, ref placement)) { return false; }
      width = placement.normalPosition.Right - placement.normalPosition.Left;
      height = placement.normalPosition.Bottom - placement.normalPosition.Top;
      showCmd = placement.showCmd;
      if (width <= 0 || height <= 0) {
        RECT rect;
        if (GetWindowRect(hwnd, out rect)) {
          width = rect.Right - rect.Left;
          height = rect.Bottom - rect.Top;
        }
      }
      return true;
    } catch { return false; }
  }

  /**
   * Bring a window forward. A minimized window is restored first (SW_RESTORE puts a
   * maximized one back maximized); a window that is already on screen is not
   * resized or moved at all. Windows then has to be asked for the foreground three
   * ways, because it only hands it over voluntarily to the process the user is
   * working with: directly, attached to the input queue of whoever holds it, and
   * with a synthetic ALT press, which makes Windows accept the request.
   */
  public static bool Focus(IntPtr hwnd) {
    if (hwnd == IntPtr.Zero) { return false; }
    try {
      int width, height, showCmd;
      Placement(hwnd, out width, out height, out showCmd);
      if (showCmd == ShowMinimized || IsIconic(hwnd)) { ShowWindow(hwnd, SwRestore); }
      if (SetForegroundWindow(hwnd)) { return true; }
      IntPtr foreground = GetForegroundWindow();
      if (foreground != IntPtr.Zero) {
        uint ignored;
        uint foregroundThread = GetWindowThreadProcessId(foreground, out ignored);
        uint targetThread = GetWindowThreadProcessId(hwnd, out ignored);
        if (foregroundThread != 0 && targetThread != 0 && foregroundThread != targetThread) {
          if (AttachThreadInput(foregroundThread, targetThread, true)) {
            bool attached = SetForegroundWindow(hwnd);
            AttachThreadInput(foregroundThread, targetThread, false);
            if (attached) { return true; }
          }
        }
      }
      keybd_event(VkMenu, 0, 0, UIntPtr.Zero);
      keybd_event(VkMenu, 0, 2, UIntPtr.Zero);
      BringWindowToTop(hwnd);
      return SetForegroundWindow(hwnd);
    } catch { return false; }
  }

  /** "class 'title'" for the log line and the self-test contract. */
  public static string Describe(IntPtr hwnd) {
    try {
      StringBuilder title = new StringBuilder(512);
      GetWindowTextW(hwnd, title, title.Capacity);
      StringBuilder cls = new StringBuilder(256);
      GetClassNameW(hwnd, cls, cls.Capacity);
      return cls.ToString() + " '" + title.ToString() + "'";
    } catch { return "(unreadable window)"; }
  }

  /**
   * Every visible, unowned window of the given window class whose title contains the
   * needle and whose resting size is at least 200x150, largest first. The class keeps
   * this to browser windows: a File Explorer window showing the app's folder carries
   * the same words in its title, and must not be mistaken for the page.
   *
   * Resting size, not the current rect: a minimized window reports a 160x28
   * placeholder through GetWindowRect, and a minimized DSH window is exactly what the
   * tray is asked to bring back.
   */
  public static IntPtr[] FindTitledWindows(string needle, string requiredClass) {
    List<IntPtr> handles = new List<IntPtr>();
    List<long> areas = new List<long>();
    try {
      EnumProc callback = delegate(IntPtr hwnd, IntPtr param) {
        if (!IsWindowVisible(hwnd) || GetWindow(hwnd, GwOwner) != IntPtr.Zero) { return true; }
        int width, height, showCmd;
        if (!Placement(hwnd, out width, out height, out showCmd)) { return true; }
        if (width < 200 || height < 150) { return true; }
        StringBuilder cls = new StringBuilder(256);
        GetClassNameW(hwnd, cls, cls.Capacity);
        if (cls.ToString() != requiredClass) { return true; }
        StringBuilder title = new StringBuilder(512);
        GetWindowTextW(hwnd, title, title.Capacity);
        if (title.ToString().IndexOf(needle, StringComparison.OrdinalIgnoreCase) < 0) { return true; }
        handles.Add(hwnd);
        areas.Add((long)width * height);
        return true;
      };
      EnumWindows(callback, IntPtr.Zero);
    } catch { }
    // Largest first: the biggest window carries the most of the page.
    for (int i = 1; i < handles.Count; i++) {
      for (int j = i; j > 0 && areas[j] > areas[j - 1]; j--) {
        long area = areas[j]; areas[j] = areas[j - 1]; areas[j - 1] = area;
        IntPtr handle = handles[j]; handles[j] = handles[j - 1]; handles[j - 1] = handle;
      }
    }
    return handles.ToArray();
  }

  /** The window class, so the self test can match a window it created itself. */
  public static string ClassOf(IntPtr hwnd) {
    try {
      StringBuilder cls = new StringBuilder(256);
      GetClassNameW(hwnd, cls, cls.Capacity);
      return cls.ToString();
    } catch { return string.Empty; }
  }

  /** The process a window belongs to, so the caller can skip the desktop app. */
  public static uint OwnerOf(IntPtr hwnd) {
    try {
      uint owner;
      GetWindowThreadProcessId(hwnd, out owner);
      return owner;
    } catch { return 0; }
  }
}

/** Chromium's dark menu palette, as measured from the desktop app's tray menu. */
public class DshTrayMenuColors : ProfessionalColorTable {
  public static readonly Color Panel = Color.FromArgb(0x1F, 0x1F, 0x1F);
  public static readonly Color Hover = Color.FromArgb(0x36, 0x36, 0x36);
  public static readonly Color Line = Color.FromArgb(0x5E, 0x5E, 0x5E);
  public static readonly Color Text = Color.FromArgb(0xE3, 0xE3, 0xE3);

  public override Color ToolStripDropDownBackground { get { return Panel; } }
  public override Color MenuBorder { get { return Panel; } }
  public override Color MenuItemBorder { get { return Hover; } }
  public override Color MenuItemSelected { get { return Hover; } }
  public override Color MenuItemSelectedGradientBegin { get { return Hover; } }
  public override Color MenuItemSelectedGradientEnd { get { return Hover; } }
  public override Color ImageMarginGradientBegin { get { return Panel; } }
  public override Color ImageMarginGradientMiddle { get { return Panel; } }
  public override Color ImageMarginGradientEnd { get { return Panel; } }
  public override Color SeparatorDark { get { return Line; } }
  public override Color SeparatorLight { get { return Line; } }
}

/** Applies the palette and drops the frame the default renderer would draw. */
public class DshTrayMenuRenderer : ToolStripProfessionalRenderer {
  /** Left inset of the item text, set from the measured metric (scaled). */
  public static int TextInsetPx = 20;

  /** How far below the item box's centre the app's labels sit, scaled. */
  public static int TextDropPx = 1;

  public DshTrayMenuRenderer() : base(new DshTrayMenuColors()) { RoundedEdges = false; }

  /** The app's menu has no border line: the panel just ends. */
  protected override void OnRenderToolStripBorder(ToolStripRenderEventArgs e) { }

  /** The app's separator runs the full panel width; WinForms would inset it. */
  protected override void OnRenderSeparator(ToolStripSeparatorRenderEventArgs e) {
    Rectangle bounds = e.Item.Bounds;
    using (Pen pen = new Pen(DshTrayMenuColors.Line)) {
      e.Graphics.DrawLine(pen, 0, bounds.Height / 2, e.ToolStrip.Width, bounds.Height / 2);
    }
  }

  /**
   * The app centres each item's text in its 28 px box; the default renderer
   * leaves it about 4 px high, because the rectangle it draws into is the item
   * bounds *inflated* by the padding instead of the padded content box. The text
   * is therefore re-placed symmetrically, keeping the app's left inset.
   *
   * The rectangle is in the item's own coordinates, so only the item's height
   * matters here — adding the item's top offset would push every row but the
   * first out of its own box and clip it away.
   */
  /**
   * The app centres each item's text in its 28 px box, insets it 20 px, and
   * paints it heavy: Chromium's text covers 388 solid-stroke pixels plus 173
   * anti-aliasing pixels for one label, where GDI's ClearType gives 272 solid,
   * which reads as thin and dim. GDI+ ClearType drawn twice gives 413 solid and
   * 188 fringe — the same distribution — so the label is drawn here rather than
   * by the base renderer, placed by the glyph band DshTrayText measures with the
   * same call.
   */
  protected override void OnRenderItemText(ToolStripItemTextRenderEventArgs e) {
    e.TextColor = DshTrayMenuColors.Text;
    try {
      Font font = e.TextFont != null ? e.TextFont : e.Item.Font;
      Rectangle ink = DshTrayText.InkBox(e.Text, font);
      // The measured ink box, not the item bounds: the ink starts at the app's
      // inset and is centred vertically on the band the eye sees.
      float left = e.Item.Bounds.Left + TextInsetPx - ink.Left;
      float top = (e.Item.Bounds.Height - ink.Height) / 2f - ink.Top + TextDropPx;
      TextRenderingHint previous = e.Graphics.TextRenderingHint;
      try {
        e.Graphics.TextRenderingHint = TextRenderingHint.ClearTypeGridFit;
        using (SolidBrush brush = new SolidBrush(DshTrayMenuColors.Text)) {
          // The second pass over the same pixels is what brings the stroke
          // coverage up to the app's; the colour itself stays #E3E3E3.
          e.Graphics.DrawString(e.Text, font, brush, left, top, StringFormat.GenericTypographic);
          e.Graphics.DrawString(e.Text, font, brush, left, top, StringFormat.GenericTypographic);
        }
      } finally {
        e.Graphics.TextRenderingHint = previous;
      }
      return;
    } catch { }
    base.OnRenderItemText(e);
  }
}

/**
 * Windows 11's own rounded corners and shadow for the popup. Clipping the panel
 * with a Region gives the same shape with hard, aliased edges and no real
 * shadow, so the corners are asked of the window manager instead
 * (DWMWA_WINDOW_CORNER_PREFERENCE, available since Windows 11 22000). The radius
 * is then Windows' own rather than the app's 12 px — that is the one measurement
 * this trades away.
 */
public static class DshTrayCorners {
  private const int CornerPreference = 33; // DWMWA_WINDOW_CORNER_PREFERENCE
  private const int BorderColor = 34;      // DWMWA_BORDER_COLOR
  private const int CornerRound = 2;       // DWMWCP_ROUND
  private const int ColorNone = unchecked((int)0xFFFFFFFE); // DWMWA_COLOR_NONE

  [DllImport("dwmapi.dll")] private static extern int DwmSetWindowAttribute(IntPtr hwnd, int attribute, ref int value, int size);
  [DllImport("dwmapi.dll")] private static extern int DwmGetWindowAttribute(IntPtr hwnd, int attribute, out int value, int size);

  /**
   * Rounds the popup and removes the 1 px window border Windows draws around a
   * rounded window (visible as a light arc against a dark panel; the app's menu
   * has no border).
   * @returns whether Windows accepted the rounding request (false before Win11).
   */
  public static bool Apply(IntPtr hwnd) {
    try {
      int preference = CornerRound;
      bool rounded = DwmSetWindowAttribute(hwnd, CornerPreference, ref preference, sizeof(int)) == 0;
      try {
        int none = ColorNone;
        DwmSetWindowAttribute(hwnd, BorderColor, ref none, sizeof(int));
      } catch { }
      return rounded;
    } catch { return false; }
  }

  /** Reads the preference back: 2 means Windows is rounding this window. */
  public static int Read(IntPtr hwnd) {
    try {
      int preference;
      if (DwmGetWindowAttribute(hwnd, CornerPreference, out preference, sizeof(int)) != 0) { return -1; }
      return preference;
    } catch { return -1; }
  }
}

/** The app's menu font: the system UI family at 9pt, as measured on this screen. */
public static class DshTrayFont {
  /**
   * The desktop app's labels are drawn in the system UI font, which on this
   * machine resolves to Microsoft YaHei UI 9pt: that is the font whose ink box
   * matches the app's own menu exactly (134 x 13 px for 打开 DeepSeek Harness,
   * where Segoe UI 9pt gives 125 x 14 and Microsoft YaHei UI 12pt gives 188 x 21).
   * An English system falls back to Segoe UI, which is what the app uses there.
   */
  public static Font MenuFont(float size) {
    string[] preferred = { "Microsoft YaHei UI", "Microsoft YaHei", "Segoe UI" };
    foreach (string family in preferred) {
      try {
        using (FontFamily probe = new FontFamily(family)) {
          return new Font(family, size, FontStyle.Regular, GraphicsUnit.Point);
        }
      } catch { }
    }
    return SystemFonts.DefaultFont;
  }
}

/** Where a label's glyphs really sit, so item text can be centred at any DPI. */
public static class DshTrayText {
  private static readonly System.Collections.Generic.Dictionary<string, Rectangle> Cache = new System.Collections.Generic.Dictionary<string, Rectangle>();

  /**
   * The ink box of the given text in the given font: drawn once with the very
   * call the renderer uses, then scanned. Two things depend on it and neither can
   * be taken from WinForms:
   *
   * - the vertical band, because the line box carries the font's descent and
   *   these labels have no descenders (the default renderer looks ~4 px high),
   * - the width the panel is sized to, because a ToolStripMenuItem's *preferred*
   *   width also reserves the image margin (measured: 214 px of content for a
   *   175 px label, and the drop-down width then varies between shows — 175 px in
   *   one run, 214 in another, which is what left the long blank area on the
   *   right).
   */
  public static Rectangle InkBox(string text, Font font) {
    string key = font.Name + "|" + font.SizeInPoints + "|" + font.GdiCharSet + "|" + text;
    Rectangle cached;
    if (Cache.TryGetValue(key, out cached)) { return cached; }
    Rectangle result = Rectangle.Empty;
    try {
      using (Bitmap probe = new Bitmap(1, 1)) {
        using (Graphics measure = Graphics.FromImage(probe)) {
          SizeF size = measure.MeasureString(text, font, PointF.Empty, StringFormat.GenericTypographic);
          int width = (int)Math.Ceiling(size.Width) + 4;
          int height = (int)Math.Ceiling(size.Height) + 4;
          if (width > 0 && height > 0) {
            using (Bitmap canvas = new Bitmap(width, height)) {
              using (Graphics canvasGraphics = Graphics.FromImage(canvas)) {
                canvasGraphics.Clear(Color.Black);
                canvasGraphics.TextRenderingHint = TextRenderingHint.ClearTypeGridFit;
                using (SolidBrush brush = new SolidBrush(Color.White)) {
                  canvasGraphics.DrawString(text, font, brush, 0, 0, StringFormat.GenericTypographic);
                  canvasGraphics.DrawString(text, font, brush, 0, 0, StringFormat.GenericTypographic);
                }
              }
              int left = -1;
              int right = -1;
              int top = -1;
              int bottom = -1;
              for (int y = 0; y < canvas.Height; y++) {
                for (int x = 0; x < canvas.Width; x++) {
                  if (canvas.GetPixel(x, y).R > 40) {
                    if (left < 0 || x < left) { left = x; }
                    if (x > right) { right = x; }
                    if (top < 0) { top = y; }
                    bottom = y;
                  }
                }
              }
              if (left >= 0 && top >= 0) {
                result = new Rectangle(left, top, right - left + 1, bottom - top + 1);
              }
            }
          }
        }
      }
    } catch { }
    if (result.Width <= 0 || result.Height <= 0) { result = new Rectangle(0, 0, font.Height * 5, font.Height); }
    Cache[key] = result;
    return result;
  }
}
'@

# The menu is sized in 96-DPI units and scaled to this display, and a WinForms
# menu needs visual styles or its renderer falls back to system colours:
# both are process-wide switches that must be set before the first window.
$dpiScale = 1.0
function Initialize-MenuStyle {
  try {
    if (-not ('DshTrayMenuRenderer' -as [type])) {
      Add-Type -TypeDefinition $menuStyleSource -ReferencedAssemblies System.Windows.Forms, System.Drawing
    }
    [DshTraySetup]::Enable()
    $script:dpiScale = [System.Drawing.Graphics]::FromHwnd([IntPtr]::Zero).DpiX / 96.0
  } catch {
    Write-TrayLog 'WARN' ('could not apply the dark menu style: {0}' -f $_.Exception.Message)
  }
}

function Get-Scaled([int]$value) {
  return [int][Math]::Round($value * $script:dpiScale)
}

function Update-MenuCorners {
  # Windows draws the rounded corners and the shadow itself, with real
  # anti-aliasing; a Region clip would cut the same shape out of the panel with
  # hard edges and no shadow at all.
  try {
    if (-not [DshTrayCorners]::Apply($script:trayMenu.Handle)) {
      Write-TrayLog 'WARN' 'could not ask Windows for rounded corners; the menu has square ones'
    }
  } catch {}
  # Re-assert the tool-window style after the show too: Explorer decides what to list
  # once the window is up, and the self test reads the resulting style back.
  try { [DshTrayWindow]::MarkToolWindow($script:trayMenu.Handle) } catch {}
}

function Close-Tray([switch]$StopDsh) {
  # The exit entry says "退出 DeepSeek Harness", so it stops the WSL instance this
  # shortcut started (through the generated stop script, hidden and not awaited).
  # -StopDsh stays off for the self test, which must never touch WSL.
  if ($StopDsh) {
    Stop-Dsh
    Write-TrayLog 'INFO' 'tray exit requested; DSH stop was asked for'
  } else {
    Write-TrayLog 'INFO' 'tray exit requested; DSH keeps running'
  }
  try {
    $tray.Visible = $false
    $tray.Dispose()
  } catch {}
  [System.Windows.Forms.Application]::Exit()
}

Initialize-MenuStyle

# The app's own menu font: the system UI family at 9pt (measured — see
# DshTrayFont), not the Windows menu font, which is Microsoft YaHei UI 12pt here.
$menuFont = [DshTrayFont]::MenuFont(9)
$panelPadding = Get-Scaled $panelPaddingPx
# The item box is a fixed height in the app. A ToolStripMenuItem is its text plus
# this padding plus a 2 px inset on each side, which is why the box is 4 px
# taller than text + padding; the padding is whatever is left of the height.
$itemHeight = Get-Scaled $itemHeightPx
$itemVerticalPadding = [Math]::Max(0, [int](($itemHeight - $menuFont.Height - 4) / 2))
$itemPadding = New-Object System.Windows.Forms.Padding((Get-Scaled $itemTextInsetPx), $itemVerticalPadding, (Get-Scaled $itemTextInsetPx), $itemVerticalPadding)

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$script:trayMenu = $menu
$menu.ShowImageMargin = $false
$menu.ShowCheckMargin = $false
$menu.DropShadowEnabled = $true
$menu.BackColor = [DshTrayMenuColors]::Panel
$menu.ForeColor = [DshTrayMenuColors]::Text
$menu.Font = $menuFont
$menu.Renderer = New-Object DshTrayMenuRenderer
[DshTrayMenuRenderer]::TextInsetPx = (Get-Scaled $itemTextInsetPx)
[DshTrayMenuRenderer]::TextDropPx = (Get-Scaled $itemTextDropPx)

# The panel is sized from the labels themselves. Left to itself, WinForms sizes a
# menu item from its *preferred* width, which also reserves the image margin — a
# 175 px label came out as 214 px of content, and the drop-down's own width then
# varied between 175 and 214 px from one show to the next, which is what left a
# long blank strip on the right. Measuring the ink and setting both the items and
# the panel leaves the app's 20 px on each side, always.
$itemInset = Get-Scaled $itemTextInsetPx
$inkWidth = 0
foreach ($label in @($openLabel, $exitLabel)) {
  $inkWidth = [Math]::Max($inkWidth, [DshTrayText]::InkBox($label, $menuFont).Width)
}
$panelWidth = $inkWidth + 2 * $itemInset

$openItem = $menu.Items.Add($openLabel)
$openItem.Padding = $itemPadding
# WinForms gives a drop-down 2 px of its own padding and ignores an assigned one,
# so the panel's top and bottom gaps are item margins, shortened by that 2 px.
# Item margins also match the app: its hover highlight stops short of the panel
# edges, which is what a margin (unlike padding) produces.
$panelMargin = [Math]::Max(0, $panelPadding - $menu.Padding.Top)
$openItem.Margin = New-Object System.Windows.Forms.Padding(0, $panelMargin, 0, 0)
$openItem.AutoSize = $false
$openItem.Size = New-Object System.Drawing.Size($panelWidth, $itemHeight)
$openItem.Add_Click({ Start-OpenFlow })

# A separator carrying the app's whole gap: 18 px with the 1 px line centred.
$separator = New-Object System.Windows.Forms.ToolStripSeparator
$separator.AutoSize = $false
$separator.Size = New-Object System.Drawing.Size($panelWidth, (Get-Scaled $separatorGapPx))
$menu.Items.Add($separator) | Out-Null

$exitItem = $menu.Items.Add($exitLabel)
$exitItem.Padding = $itemPadding
$exitItem.Margin = New-Object System.Windows.Forms.Padding(0, 0, 0, $panelMargin)
$exitItem.AutoSize = $false
$exitItem.Size = New-Object System.Drawing.Size($panelWidth, $itemHeight)
$exitItem.Add_Click({ Close-Tray -StopDsh })

$panelHeight = $menu.Padding.Top + $panelMargin + $itemHeight + (Get-Scaled $separatorGapPx) + $itemHeight + $panelMargin + $menu.Padding.Bottom
$menu.AutoSize = $false
$menu.Size = New-Object System.Drawing.Size($panelWidth, $panelHeight)

$menu.Add_Opened({ Update-MenuCorners })
# Before the first show, so Windows never gives the popup a taskbar button or an
# Alt-Tab entry in the first place (the handle is created here on purpose).
$menu.Add_Opening({ try { [DshTrayWindow]::MarkToolWindow($script:trayMenu.Handle) } catch {} })

# The tray icon itself. It wears the inverted twin of the shortcut icon so it can
# be told apart from the official desktop app's icon at a glance.
$tray = New-Object System.Windows.Forms.NotifyIcon
$trayFile = $iconPath
if (Test-Path -LiteralPath $trayIconPath) { $trayFile = $trayIconPath }
try {
  # Load the frame that matches the notification area: the Icon(path)
  # constructor would take the 32x32 default frame and let WinForms scale it
  # down, which shows a soft, muddy mark.
  $tray.Icon = New-Object System.Drawing.Icon($trayFile, [System.Windows.Forms.SystemInformation]::SmallIconSize)
} catch {
  $tray.Icon = [System.Drawing.SystemIcons]::Application
}
$tray.Text = $shortcutName

# Left click shows DSH (the desktop app's own tray behaves that way), right click
# opens the menu. The menu is shown by hand rather than assigned to the
# NotifyIcon, because WinForms would also open it on a single left click.
$tray.Add_MouseUp({
  param($sender, $eventArgs)
  if ($eventArgs.Button -eq [System.Windows.Forms.MouseButtons]::Left) {
    Start-OpenFlow
  } elseif ($eventArgs.Button -eq [System.Windows.Forms.MouseButtons]::Right) {
    Show-TrayMenu
  }
})

function Show-TrayMenu {
  try {
    # Anchored at the cursor like the desktop app's own menu: its bottom-left
    # corner sits on the pointer and it grows up and to the right (measured on the
    # app: a click at 2169,1416 puts the panel's bottom-left at 2169,1416). The
    # WinForms default — passing the cursor as the menu's top-left — parks it above
    # the taskbar inside the working area instead, which is the Windows convention
    # but not the app's. Windows still clamps it at the screen edges, as Chromium
    # does, and the height is known because the panel is sized explicitly.
    $cursor = [System.Windows.Forms.Cursor]::Position
    $menu.Show($cursor.X, $cursor.Y - $script:trayMenu.Height)
  } catch {
    Write-TrayLog 'WARN' ('could not open the tray menu: {0}' -f $_.Exception.Message)
  }
}

# ---- self test (no UI) ----
if ($SelfTest) {
  # The contract goes to a UTF-8 file next to the helper as well as to stdout:
  # redirected stdout runs through the console code page, which mangles the
  # Chinese menu labels for anything parsing it.
  $target = Get-ShortcutTarget
  # Rounded corners are a DWM request, so prove it on a real window: a 10x10
  # form parked off-screen, never shown to anyone.
  $dwmReadBack = -1
  $dwmProbe = New-Object System.Windows.Forms.Form
  $dwmProbe.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::None
  $dwmProbe.ShowInTaskbar = $false
  $dwmProbe.StartPosition = [System.Windows.Forms.FormStartPosition]::Manual
  $dwmProbe.Location = New-Object System.Drawing.Point(-32000, -32000)
  $dwmProbe.Size = New-Object System.Drawing.Size(10, 10)
  $dwmProbe.Opacity = 0
  try {
    $dwmProbe.Show()
    [DshTrayCorners]::Apply($dwmProbe.Handle) | Out-Null
    $dwmReadBack = [DshTrayCorners]::Read($dwmProbe.Handle)
  } catch {
  } finally {
    try { $dwmProbe.Close(); $dwmProbe.Dispose() } catch {}
  }
  # Style the popup exactly as the live path does (Opening/Opened fire only on a real
  # show, which the self test never performs), so the contract can assert the bits.
  [DshTrayWindow]::MarkToolWindow($menu.Handle)

  # Prove the window matcher on a window we own, and the focus call on the same one:
  # that is the code path the tray's "reuse first" step uses, without touching anyone
  # else's window.
  $matcherProbe = New-Object System.Windows.Forms.Form
  $matcherProbe.Text = 'dsh-web-tray matcher probe'
  $matcherProbe.StartPosition = 'Manual'
  $matcherProbe.Location = New-Object System.Drawing.Point(0, 0)
  $matcherProbe.Size = New-Object System.Drawing.Size(240, 160)
  $matcherProbe.Show()
  Start-Sleep -Milliseconds 200
  # The probe's own class name carries a per-process hash, so it is read back rather
  # than guessed: the matcher takes the class it must match.
  $matcherFoundOwnWindow = (@([DshTrayTarget]::FindTitledWindows('dsh-web-tray matcher', [DshTrayTarget]::ClassOf($matcherProbe.Handle))) -contains $matcherProbe.Handle)
  $focusReturned = [DshTrayTarget]::Focus($matcherProbe.Handle)
  $matcherProbe.Close()
  $matcherProbe.Dispose()
  $dshWindow = Find-DshWindow

  $contract = [ordered]@{
    openLabel = $openLabel
    exitLabel = $exitLabel
    items = @($menu.Items | ForEach-Object { $_.GetType().Name + '|' + $_.Text })
    # Measured, not assumed: the renderer has to be the styled one, and visual
    # styles have to be on or that renderer paints system colours.
    renderer = $menu.Renderer.GetType().Name
    visualStyles = [System.Windows.Forms.Application]::RenderWithVisualStyles
    backColor = $menu.BackColor.ToArgb()
    foreColor = $menu.ForeColor.ToArgb()
    hoverColor = [DshTrayMenuColors]::Hover.ToArgb()
    separatorColor = [DshTrayMenuColors]::Line.ToArgb()
    font = $menu.Font.Name + ' ' + $menu.Font.Size
    fontHeight = $menu.Font.Height
    itemPadding = @($openItem.Padding.Left, $openItem.Padding.Top, $openItem.Padding.Right, $openItem.Padding.Bottom)
    itemMargin = @($openItem.Margin.Top, $exitItem.Margin.Bottom)
    # WinForms' own drop-down padding, which the item margins above are
    # shortened by; the two together are the app's 12 px panel gap.
    panelPaddingTop = $menu.Padding.Top
    separatorHeight = $separator.Height
    # The panel is measured, not left to WinForms: width from the label ink plus
    # the app's inset on both sides, so the blank strip on the right is the same as
    # on the left (the app's own menu is 175 px for a 134 px label).
    inkWidth = $inkWidth
    textInset = $itemInset
    textDrop = [DshTrayMenuRenderer]::TextDropPx
    panelWidth = $menu.Width
    panelHeight = $menu.Height
    itemWidth = $openItem.Width
    panelRightGap = $menu.Width - $itemInset - $inkWidth
    # Corners come from Windows (dwm), not from a Region clip: 2 = rounded.
    cornerMode = 'dwm'
    dwmCornerReadBack = $dwmReadBack
    # The popup must be a tool window, or Explorer lists it as an app window of this
    # PowerShell process (which is what named the menu "Windows PowerShell").
    menuExStyle = [DshTrayWindow]::ExStyleOf($menu.Handle)
    toolWindow = (([DshTrayWindow]::ExStyleOf($menu.Handle) -band 0x80) -ne 0)
    # "Reuse first": a browser window (installed web app, else a tab window) that
    # already shows the page. The Electron desktop app is never a candidate — the
    # count below says how many of its windows the matcher skipped.
    dshWindowFound = ($dshWindow.Handle -ne [IntPtr]::Zero)
    dshWindow = $dshWindow.Description
    dshWindowIsWebApp = $dshWindow.WebApp
    dshWindowsSkippedAsApp = $dshWindow.SkippedApp
    matcherFoundOwnWindow = $matcherFoundOwnWindow
    focusReturned = $focusReturned
    itemHeight = $itemHeight
    dpiScale = $script:dpiScale
    targetPath = $target.Path
    targetArguments = $target.Arguments
    trayIcon = (Split-Path -Leaf $trayFile)
    shortcutIcon = (Split-Path -Leaf $iconPath)
    webUrl = $webUrl
    dshAlive = (Test-DshAlive)
    openTimeoutSec = $openTimeoutSec
    trayText = $tray.Text
  } | ConvertTo-Json -Compress -Depth 4
  try {
    Set-Content -Path (Join-Path $scriptDir 'tray-selftest.json') -Value $contract -Encoding UTF8
  } catch {}
  Write-Output $contract
  # Exercise the real exit handler as well: it has to return on its own, because
  # it must not touch WSL (which is what used to freeze the tray).
  Close-Tray
  return
}

# ---- single instance ----
$mutex = New-Object System.Threading.Mutex($false, '${mutexName()}')
try {
  if (-not $mutex.WaitOne(0, $false)) {
    # The tray is up already, so this double-click only has to show DSH.
    $tray.Dispose()
    Invoke-OpenFlowAndWait
    return
  }
} catch {
  return
}

$openTimer = New-Object System.Windows.Forms.Timer
$openTimer.Interval = 2000
$openTimer.Add_Tick({
  if (Test-DshAlive) {
    $openTimer.Stop()
    $script:opening = $false
    Open-DshPage
    return
  }
  if ((Get-Date) -gt $script:openDeadline) {
    $openTimer.Stop()
    $script:opening = $false
    Write-TrayLog 'WARN' ('gave up waiting for {0} after {1}s' -f $webUrl, $openTimeoutSec)
  }
})
$script:openTimer = $openTimer

$tray.Visible = $true
# Tray mode from here on: give up the inherited console (the command-line flags
# above have already returned, and they need theirs for output).
[DshTraySetup]::DetachConsole()
Write-TrayLog 'INFO' ('tray started (menu: {0} / {1})' -f $openLabel, $exitLabel)

# The desktop shortcut exists to show DSH, so a fresh tray opens it right away.
Start-OpenFlow

[System.Windows.Forms.Application]::Run()

try {
  $openTimer.Stop()
  $tray.Visible = $false
  $tray.Dispose()
} catch {}
try {
  $mutex.ReleaseMutex()
} catch {}
`;
}
