/**
 * The generated Windows-side tray helper.
 *
 * This is the one process deliberately independent of DSH: it must start DSH,
 * stop it when idle, and keep the switches honoured while `dsh web` is down.
 * Upstream baked the watchdog tuning into the generated text, so changing a
 * value needed a regenerate plus a tray restart. Here the helper re-reads
 * `tray-config.json` on every tick, and the baked JSON is only the fallback
 * default.
 *
 * The generated script is deliberately plain PowerShell 5.1: no modules, no
 * `Get-NetTCPConnection` (measured: it reports zero connections for WSL-owned
 * loopback sockets), just `netstat.exe` parsing and WinForms.
 */
import { DEFAULT_TRAY_CONFIG, TRAY_CONFIG_NAME } from "./config.js";
import { ICON_FILE_NAME, PLUGIN_ID, TRAY_LOG_NAME, TRAY_STATUS_NAME, TRAY_VBS_NAME, } from "./names.js";
/** Single-instance mutex name; one tray per user session. */
function mutexName() {
    return `Local\\${PLUGIN_ID}-single`;
}
/**
 * Escape a value baked into a PowerShell single-quoted string. JSON escaping is
 * NOT PowerShell escaping: a double-quoted PS string interpolates `$` and
 * treats `"` as a terminator, so baked values use single quotes with the `''`
 * doubling rule.
 */
function psSingleQuoted(value) {
    return `'${value.replace(/'/g, "''")}'`;
}
/** `\\wsl.localhost\<distro>\home\me\.dsh\dsh-web-tray\start.log` from a WSL path. */
export function wslLogUncPath(distro, wslLogPath) {
    const relative = wslLogPath.replace(/^\/+/, '').replace(/\//g, '\\');
    return `\\\\wsl.localhost\\${distro}\\${relative}`;
}
/**
 * Build the Windows tray helper, including the watchdog state machine, the
 * runtime switch reader, the idle counter and the status writer.
 *
 * Watchdog phases: `starting` (initial boot grace) → `probing` (steady state)
 * → `restarting` (after a restart trigger, waiting for DSH to answer) →
 * `backoff` (cooldown after a failed restart) or `paused` (auto-give-up after
 * `maxRestartFailures`, or the watchdog switch is off). `stopped` means DSH was
 * stopped on purpose (tray menu or the idle timer) and must not be restarted
 * until it answers again.
 *
 * @param config - launch facts baked into the script.
 * @param defaults - the config a fresh install starts from; `tray-config.json`
 *   overrides every field at runtime.
 */
export function buildTrayScript(config, defaults = DEFAULT_TRAY_CONFIG) {
    const distro = psSingleQuoted(config.distro);
    const webUrl = psSingleQuoted(config.webUrl);
    const shortcutName = psSingleQuoted(config.shortcutName);
    const wslStartScript = psSingleQuoted(config.wslStartScript);
    const wslStopScript = psSingleQuoted(config.wslStopScript);
    const wslStartLogUnc = psSingleQuoted(wslLogUncPath(config.distro, config.wslStartLogPath));
    const defaultConfigJson = psSingleQuoted(JSON.stringify(defaults));
    return `# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
param(
  [switch]$Regenerate,
  [switch]$SelfTest
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$distro = ${distro}
$webUrl = ${webUrl}
$shortcutName = ${shortcutName}
$wslStartScript = ${wslStartScript}
$wslStopScript = ${wslStopScript}
$wslStartLogUnc = ${wslStartLogUnc}
$scriptDir = Split-Path -Parent $PSCommandPath
$iconPath = Join-Path $scriptDir '${ICON_FILE_NAME}'
$vbsPath = Join-Path $scriptDir '${TRAY_VBS_NAME}'
$configPath = Join-Path $scriptDir '${TRAY_CONFIG_NAME}'
$trayLogPath = Join-Path $scriptDir '${TRAY_LOG_NAME}'
$trayStatusPath = Join-Path $scriptDir '${TRAY_STATUS_NAME}'
$trayLogMaxBytes = 512 * 1024
$trayLogKeepLines = 1000
$webPort = ([uri]$webUrl).Port

# ---- runtime configuration ----
# The baked JSON is only the fallback; Read-TrayConfig replaces it every tick
# with whatever tray-config.json says, so a switch change needs no regenerate.
$defaultConfigJson = ${defaultConfigJson}
$script:cfg = $defaultConfigJson | ConvertFrom-Json
$script:cfgSource = 'defaults'

# ---- mutable state (hashtables so timer/menu handlers share it) ----
$script:probe = @{ ok = $false; detail = ''; ms = 0 }
$script:wd = @{
  phase = 'starting'          # starting|probing|restarting|backoff|paused|stopped
  probeFailures = 0
  restartFailures = 0
  restartCount = 0
  lastAliveAt = $null
  lastRestartAt = $null
  lastRestartOk = $null       # $null=unknown, $true=ok, $false=failed
  restartDeadline = $null
  backoffDeadline = $null
  autoPaused = $false
  stoppedIntentionally = $false
  lastThrottleAt = $null
}
$script:idle = @{ connections = $null; idleSeconds = 0; sampledAt = $null }
$script:actions = New-Object System.Collections.ArrayList
$script:lastTickAt = $null
$script:lastError = $null
$script:procNames = @{}
$script:procNamesAt = $null
$script:startedByTray = $false
$script:readyDeadline = $null

function Write-TrayLog {
  param([string]$Level, [string]$Message)
  try {
    $line = '{0} | {1,-5} | {2}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'), $Level, $Message
    Add-Content -Path $trayLogPath -Value $line -Encoding UTF8
    try {
      $len = (Get-Item $trayLogPath -ErrorAction SilentlyContinue).Length
      if ($len -gt $trayLogMaxBytes) {
        $tail = Get-Content -Path $trayLogPath -Tail $trayLogKeepLines -Encoding UTF8
        Set-Content -Path $trayLogPath -Value $tail -Encoding UTF8
        Add-Content -Path $trayLogPath -Value ('{0} | INFO  | tray log rotated (kept last {1} lines)' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff'), $trayLogKeepLines) -Encoding UTF8
      }
    } catch {}
  } catch {}
}

# Avoid log spam during long waits: at most one line per throttled interval.
function Write-TrayLogThrottled([string]$Message) {
  $now = Get-Date
  if ($script:wd.lastThrottleAt -eq $null -or ($now - $script:wd.lastThrottleAt).TotalSeconds -ge 30) {
    Write-TrayLog 'INFO' $Message
    $script:wd.lastThrottleAt = $now
  }
}

function Add-TrayAction([string]$Action, [bool]$Ok, [string]$Detail) {
  try {
    [void]$script:actions.Add([ordered]@{
      at = (Get-Date).ToString('o')
      action = $Action
      ok = $Ok
      detail = $Detail
    })
    while ($script:actions.Count -gt 10) { $script:actions.RemoveAt(0) }
  } catch {}
}

function Get-BoolOr($value, $fallback) {
  if ($value -is [bool]) { return $value }
  return $fallback
}

function Get-IntOr([string]$value, [int]$min, [int]$max, [int]$fallback) {
  $parsed = 0
  if (-not [int]::TryParse([string]$value, [ref]$parsed)) { return $fallback }
  if ($parsed -lt $min) { return $min }
  if ($parsed -gt $max) { return $max }
  return $parsed
}

function Get-ExcludeList($value, [string[]]$fallback) {
  $names = @()
  if ($value -ne $null) {
    foreach ($entry in @($value)) {
      if ($entry -is [string] -and $entry.Trim() -ne '') {
        $names += ($entry.Trim().ToLower() -replace '\\.exe$', '')
      }
    }
  }
  if ($names.Count -eq 0) { return $fallback }
  return $names
}

# Re-read tray-config.json. A missing file means the baked defaults; an
# unreadable one keeps the last good values so a half-written file cannot
# silently disable a switch.
function Read-TrayConfig {
  if (-not (Test-Path -LiteralPath $configPath)) {
    if ($script:cfgSource -ne 'defaults') { $script:cfgSource = 'defaults' }
    return
  }
  $parsed = $null
  try {
    $parsed = (Get-Content -LiteralPath $configPath -Raw -Encoding UTF8) | ConvertFrom-Json
  } catch {
    $script:cfgSource = 'last-good'
    Write-TrayLogThrottled ('tray-config.json is unreadable ({0}); keeping the last good values' -f $_.Exception.Message)
    return
  }
  if ($parsed -eq $null) {
    $script:cfgSource = 'last-good'
    return
  }
  $current = $script:cfg
  $script:cfg = [pscustomobject]@{
    version = 1
    autoStart = Get-BoolOr $parsed.autoStart $current.autoStart
    autoStopOnExit = Get-BoolOr $parsed.autoStopOnExit $current.autoStopOnExit
    autoStopIdleMinutes = Get-IntOr $parsed.autoStopIdleMinutes 0 1440 $current.autoStopIdleMinutes
    watchdogEnabled = Get-BoolOr $parsed.watchdogEnabled $current.watchdogEnabled
    probeIntervalSec = Get-IntOr $parsed.probeIntervalSec 2 300 $current.probeIntervalSec
    probeTimeoutSec = Get-IntOr $parsed.probeTimeoutSec 1 30 $current.probeTimeoutSec
    downThreshold = Get-IntOr $parsed.downThreshold 1 10 $current.downThreshold
    restartWaitSec = Get-IntOr $parsed.restartWaitSec 30 1800 $current.restartWaitSec
    maxRestartFailures = Get-IntOr $parsed.maxRestartFailures 1 10 $current.maxRestartFailures
    restartBackoffSec = Get-IntOr $parsed.restartBackoffSec 0 600 $current.restartBackoffSec
    idleProbeExcludeProcesses = Get-ExcludeList $parsed.idleProbeExcludeProcesses $current.idleProbeExcludeProcesses
  }
  $script:cfgSource = 'file'
}

# Write the switches the tray menu changed, so the settings card and the next
# tick agree. Temp file + move keeps a reader from seeing a half-written JSON.
function Save-TrayConfig {
  try {
    $tmp = $configPath + '.tmp'
    Set-Content -Path $tmp -Value ($script:cfg | ConvertTo-Json -Depth 4) -Encoding UTF8
    Move-Item -LiteralPath $tmp -Destination $configPath -Force
    $script:cfgSource = 'file'
  } catch {
    Write-TrayLog 'ERROR' ('could not write tray-config.json: {0}' -f $_.Exception.Message)
  }
}

# ---- Windows helpers ----

function New-DshShortcut {
  $desktop = [Environment]::GetFolderPath('Desktop')
  $lnkPath = Join-Path $desktop ($shortcutName + '.lnk')
  $shell = New-Object -ComObject WScript.Shell
  $shortcut = $shell.CreateShortcut($lnkPath)
  $shortcut.TargetPath = 'C:\\Windows\\System32\\wscript.exe'
  $shortcut.Arguments = '"' + $vbsPath + '"'
  $shortcut.WorkingDirectory = $scriptDir
  $shortcut.IconLocation = $iconPath + ',0'
  $shortcut.Description = 'DSH Web (WSL)'
  $shortcut.Save()
}

$launcher = New-Object -ComObject WScript.Shell

function Start-DshWsl {
  $wslCmd = 'wsl.exe -d ' + $distro + ' -- bash -lc "' + $wslStartScript + '"'
  $launcher.Run($wslCmd, 0, $false) | Out-Null
}

# Stop/start go through the generated stop.sh so every launcher flavor
# (source checkout, npm global, npx) is covered by one maintained script, and
# so the pkill pattern cannot match the wsl.exe/bash wrapper itself.
function Stop-Dsh {
  $stopCmd = 'wsl.exe -d ' + $distro + ' -- bash ' + $wslStopScript
  $launcher.Run($stopCmd, 0, $true) | Out-Null
}

# Non-blocking stop for the tick handler: it must never freeze the UI thread on
# a wsl.exe round-trip; success is judged by the URL.
function Stop-DshAsync {
  $stopCmd = 'wsl.exe -d ' + $distro + ' -- bash ' + $wslStopScript
  $launcher.Run($stopCmd, 0, $false) | Out-Null
}

function Restart-Dsh {
  Stop-Dsh
  Start-Sleep -Seconds 2
  Start-DshWsl
}

# The launch token belongs to one DSH process and is printed once per run into
# the start script's log. Reading it from the Windows side avoids a wsl.exe
# round-trip; without it the browser would land on a 401 page.
function Get-WebAuthUrl {
  try {
    if (-not (Test-Path -LiteralPath $wslStartLogUnc)) { return $null }
    $tail = @(Get-Content -LiteralPath $wslStartLogUnc -Tail 120 -Encoding UTF8 -ErrorAction Stop)
    for ($i = $tail.Count - 1; $i -ge 0; $i--) {
      if ($tail[$i] -match 'http://127\\.0\\.0\\.1:\\d+/\\?token=[A-Za-z0-9_-]+') { return $Matches[0] }
    }
  } catch {}
  return $null
}

function Open-DshPage {
  # Prefer the token URL so a browser without a cookie does not get a 401; the
  # plain URL is still right when DSH was started by hand and never logged a token.
  $auth = Get-WebAuthUrl
  $target = $webUrl
  if ($auth -ne $null) { $target = $auth }
  try { Start-Process $target } catch {}
}

# ---- idle detection ----

function Get-ProcessNameForPid([int]$processId) {
  $now = Get-Date
  if ($script:procNamesAt -eq $null -or ($now - $script:procNamesAt).TotalSeconds -ge 60) {
    $map = @{}
    try {
      foreach ($p in Get-Process -ErrorAction SilentlyContinue) { $map[[int]$p.Id] = $p.ProcessName.ToLower() }
    } catch {}
    $script:procNames = $map
    $script:procNamesAt = $now
  }
  if ($script:procNames.ContainsKey($processId)) { return $script:procNames[$processId] }
  return ''
}

# Count ESTABLISHED connections to the web port whose owner is not one of ours.
#
# Deliberately netstat, not Get-NetTCPConnection: on this machine the cmdlet
# reports ZERO rows for the WSL-owned loopback sockets while netstat lists them
# (verified: 2 ESTABLISHED + 1 CLOSE_WAIT). The exclusion list keeps this
# helper's own probe - and the WSL plumbing - from resetting the idle timer.
# Returns $null when netstat cannot be sampled at all.
function Get-IdleEstablishedCount {
  param([int]$Port, [string[]]$Exclude, [string[]]$Lines)
  if ($Lines -eq $null) {
    try {
      $Lines = @(& netstat.exe -ano 2>$null)
    } catch {
      return $null
    }
    if ($Lines.Count -eq 0) { return $null }
  }
  $count = 0
  foreach ($line in $Lines) {
    if ($line -notmatch '^\\s*TCP\\s+(\\S+):(\\d+)\\s+(\\S+):(\\d+)\\s+(\\S+)\\s+(\\d+)\\s*$') { continue }
    if ($Matches[5] -ne 'ESTABLISHED') { continue }
    if ($Matches[2] -ne [string]$Port -and $Matches[4] -ne [string]$Port) { continue }
    $owner = Get-ProcessNameForPid ([int]$Matches[6])
    if ($Exclude -contains $owner) { continue }
    $count++
  }
  return $count
}

# Pure decision for the idle stop, so -SelfTest can exercise it: any browser
# connection wins, a zero threshold means off, otherwise the timer decides.
function Test-IdleStopDue([int]$Connections, [double]$IdleSeconds, [int]$ThresholdMinutes) {
  if ($Connections -gt 0) { return $false }
  if ($ThresholdMinutes -le 0) { return $false }
  return ($IdleSeconds -ge ($ThresholdMinutes * 60))
}

function Update-Idle {
  $count = Get-IdleEstablishedCount -Port $webPort -Exclude @($script:cfg.idleProbeExcludeProcesses)
  if ($count -eq $null) {
    if ($script:idle.connections -ne $null) {
      Write-TrayLog 'WARN' 'netstat could not be sampled; idle auto-stop is disabled until it works again'
    }
    $script:idle.connections = $null
    $script:idle.idleSeconds = 0
    return
  }
  $now = Get-Date
  $delta = 0
  if ($script:lastTickAt -ne $null) { $delta = ($now - $script:lastTickAt).TotalSeconds }
  $script:lastTickAt = $now
  $script:idle.connections = $count
  $script:idle.sampledAt = $now.ToString('o')

  if ($count -gt 0) {
    if ($script:idle.idleSeconds -ge 60) { Write-TrayLog 'INFO' ('browser connection back ({0}); idle timer reset' -f $count) }
    $script:idle.idleSeconds = 0
    return
  }
  if ($script:wd.stoppedIntentionally) { return }
  $script:idle.idleSeconds = $script:idle.idleSeconds + $delta
  $threshold = [int]$script:cfg.autoStopIdleMinutes
  if (-not (Test-IdleStopDue -Connections $count -IdleSeconds $script:idle.idleSeconds -ThresholdMinutes $threshold)) { return }
  Write-TrayLog 'INFO' ('idle for {0} min with no browser connection; stopping DSH (autoStopIdleMinutes={1})' -f [math]::Floor($script:idle.idleSeconds / 60), $threshold)
  Add-TrayAction 'stop' $true ('idle {0} min; no browser connection' -f $threshold)
  Stop-DshAsync
  $script:wd.stoppedIntentionally = $true
  $script:wd.phase = 'stopped'
  $script:wd.probeFailures = 0
  $script:idle.idleSeconds = 0
}

# ---- watchdog ----

function Test-DshAlive {
  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  $script:probe.detail = ''
  try {
    $resp = Invoke-WebRequest -Uri $webUrl -UseBasicParsing -TimeoutSec $script:cfg.probeTimeoutSec
    $script:probe.ok = ($resp.StatusCode -ge 200 -and $resp.StatusCode -lt 300)
    $script:probe.detail = 'HTTP ' + $resp.StatusCode
  } catch {
    $script:probe.ok = $false
    if ($_.Exception.Response -ne $null) {
      $script:probe.detail = 'HTTP ' + [int]$_.Exception.Response.StatusCode
    } else {
      $script:probe.detail = $_.Exception.Message
    }
  } finally {
    $sw.Stop()
    $script:probe.ms = $sw.ElapsedMilliseconds
  }
}

function Invoke-WatchdogRestart {
  $script:wd.lastRestartAt = Get-Date
  $script:wd.lastRestartOk = $null
  $script:wd.restartDeadline = (Get-Date).AddSeconds($script:cfg.restartWaitSec)
  $script:wd.restartCount = $script:wd.restartCount + 1
  $attempt = $script:wd.restartFailures + 1
  Write-TrayLog 'WARN' ('triggering restart (attempt {0}/{1})' -f $attempt, $script:cfg.maxRestartFailures)
  Add-TrayAction 'restart' $true ('attempt {0}/{1}' -f $attempt, $script:cfg.maxRestartFailures)
  Stop-DshAsync
  Start-Sleep -Seconds 2
  Start-DshWsl
  $script:wd.phase = 'restarting'
}

function Enter-WatchdogFailure {
  if ($script:wd.restartFailures -ge $script:cfg.maxRestartFailures) {
    $script:wd.phase = 'paused'
    $script:wd.autoPaused = $true
    Write-TrayLog 'ERROR' ('gave up after {0} consecutive failed restart attempts; watchdog PAUSED. Resume from the tray menu, or it resumes automatically once DSH answers again.' -f $script:wd.restartFailures)
    Add-TrayAction 'restart' $false ('gave up after {0} failures' -f $script:wd.restartFailures)
  } else {
    $script:wd.phase = 'backoff'
    $script:wd.backoffDeadline = (Get-Date).AddSeconds($script:cfg.restartBackoffSec)
    Write-TrayLog 'WARN' ('next restart attempt in {0}s (backoff)' -f $script:cfg.restartBackoffSec)
  }
}

function Update-Watchdog {
  Test-DshAlive
  $alive = $script:probe.ok
  $phase = $script:wd.phase
  $now = Get-Date

  # Stopped on purpose (tray menu or idle): never restart, but notice a manual
  # start so supervision comes back on its own.
  if ($script:wd.stoppedIntentionally) {
    if ($alive) {
      $script:wd.stoppedIntentionally = $false
      $script:wd.probeFailures = 0
      $script:wd.restartFailures = 0
      $script:wd.autoPaused = $false
      $script:wd.phase = 'probing'
      $script:wd.lastAliveAt = $now
      Write-TrayLog 'INFO' 'DSH answered again after an intentional stop; watchdog resumed'
    }
    return
  }

  if ($alive) {
    $script:wd.probeFailures = 0
    $script:wd.lastAliveAt = $now
    if ($phase -eq 'starting') {
      $script:wd.phase = 'probing'
      Write-TrayLog 'INFO' ('DSH alive: {0} answered ({1}, {2}ms)' -f $webUrl, $script:probe.detail, $script:probe.ms)
    } elseif ($phase -eq 'restarting') {
      $script:wd.lastRestartOk = $true
      $script:wd.restartFailures = 0
      $script:wd.phase = 'probing'
      Write-TrayLog 'INFO' ('restart succeeded: {0} answered ({1}, {2}ms); failure count reset' -f $webUrl, $script:probe.detail, $script:probe.ms)
    } elseif ($phase -eq 'backoff') {
      $script:wd.lastRestartOk = $true
      $script:wd.restartFailures = 0
      $script:wd.phase = 'probing'
      Write-TrayLog 'INFO' 'DSH recovered during backoff; watchdog back to probing.'
    } elseif ($phase -eq 'paused' -and $script:wd.autoPaused) {
      $script:wd.autoPaused = $false
      $script:wd.restartFailures = 0
      $script:wd.phase = 'probing'
      Write-TrayLog 'INFO' 'DSH recovered while watchdog paused; watchdog resumed automatically.'
    }
    return
  }

  # The switch off means "watch, never restart".
  if (-not [bool]$script:cfg.watchdogEnabled) { return }

  if ($phase -eq 'starting') {
    if ($now -gt $script:wd.restartDeadline) {
      $script:wd.restartFailures++
      Write-TrayLog 'WARN' ('initial start never became ready within {0}s ({1}); attempt {2}/{3}' -f $script:cfg.restartWaitSec, $script:probe.detail, $script:wd.restartFailures, $script:cfg.maxRestartFailures)
      Enter-WatchdogFailure
    } else {
      Write-TrayLogThrottled ('still waiting for the initial DSH start ({0})' -f $script:probe.detail)
    }
    return
  }

  if ($phase -eq 'probing') {
    $script:wd.probeFailures++
    if ($script:wd.probeFailures -eq 1) {
      Write-TrayLog 'WARN' ('probe failed ({0}/{1}): {2} ({3})' -f $script:wd.probeFailures, $script:cfg.downThreshold, $webUrl, $script:probe.detail)
    } elseif ($script:wd.probeFailures -eq 2) {
      Write-TrayLog 'WARN' ('probe failed ({0}/{1}): {2}' -f $script:wd.probeFailures, $script:cfg.downThreshold, $script:probe.detail)
    }
    if ($script:wd.probeFailures -ge $script:cfg.downThreshold) {
      Write-TrayLog 'WARN' ('DSH considered DOWN after {0} consecutive probe failures; triggering restart. Last error: {1}' -f $script:wd.probeFailures, $script:probe.detail)
      Invoke-WatchdogRestart
    }
    return
  }

  if ($phase -eq 'restarting') {
    if ($now -gt $script:wd.restartDeadline) {
      $script:wd.restartFailures++
      $script:wd.lastRestartOk = $false
      Write-TrayLog 'WARN' ('restart attempt {0} FAILED: DSH did not answer within {1}s (last error: {2})' -f $script:wd.restartFailures, $script:cfg.restartWaitSec, $script:probe.detail)
      Enter-WatchdogFailure
    } else {
      Write-TrayLogThrottled ('restart in progress: still DOWN ({0}); giving it {1}s more' -f $script:probe.detail, [math]::Ceiling(($script:wd.restartDeadline - $now).TotalSeconds))
    }
    return
  }

  if ($phase -eq 'backoff') {
    if ($now -ge $script:wd.backoffDeadline) {
      Write-TrayLog 'WARN' ('backoff elapsed; restarting again (attempt {0}/{1})' -f ($script:wd.restartFailures + 1), $script:cfg.maxRestartFailures)
      Invoke-WatchdogRestart
    }
    return
  }

  # paused: watch silently; auto-resume is handled in the alive branch.
}

# ---- status ----

function Format-Idle {
  if ($script:idle.connections -eq $null) { return '连接数未知' }
  $threshold = [int]$script:cfg.autoStopIdleMinutes
  if ($threshold -le 0) { return ('连接 {0}' -f $script:idle.connections) }
  $left = [math]::Max(0, [math]::Ceiling(($threshold * 60 - $script:idle.idleSeconds) / 60))
  return ('连接 {0}，{1} 分钟后停服' -f $script:idle.connections, $left)
}

function Get-PhaseLabel([string]$phase) {
  if (-not [bool]$script:cfg.watchdogEnabled -and $phase -ne 'stopped') { return '已关闭' }
  switch ($phase) {
    'starting'   { return '启动中' }
    'probing'    { return '运行中' }
    'restarting' { return '重启中' }
    'backoff'    { return '冷却中' }
    'paused'     { return '已暂停' }
    'stopped'    { return '已停止' }
    default      { return $phase }
  }
}

function Write-TrayStatus {
  $now = Get-Date
  $aliveAt = $null
  if ($script:wd.lastAliveAt -ne $null) { $aliveAt = $script:wd.lastAliveAt.ToString('o') }
  $restartAt = $null
  if ($script:wd.lastRestartAt -ne $null) { $restartAt = $script:wd.lastRestartAt.ToString('o') }
  $body = [ordered]@{
    updatedAt = $now.ToString('o')
    platform = 'wsl'
    phase = $script:wd.phase
    configSource = $script:cfgSource
    switches = [ordered]@{
      autoStart = [bool]$script:cfg.autoStart
      autoStopOnExit = [bool]$script:cfg.autoStopOnExit
      autoStopIdleMinutes = [int]$script:cfg.autoStopIdleMinutes
      watchdogEnabled = [bool]$script:cfg.watchdogEnabled
    }
    probe = [ordered]@{
      ok = [bool]$script:probe.ok
      detail = $script:probe.detail
      latencyMs = [int]$script:probe.ms
      failures = [int]$script:wd.probeFailures
      downThreshold = [int]$script:cfg.downThreshold
    }
    restarts = [ordered]@{
      count = [int]$script:wd.restartCount
      failures = [int]$script:wd.restartFailures
      maxFailures = [int]$script:cfg.maxRestartFailures
      lastAt = $restartAt
      lastOk = $script:wd.lastRestartOk
    }
    idle = [ordered]@{
      connections = $script:idle.connections
      idleSeconds = [math]::Round($script:idle.idleSeconds)
      thresholdMinutes = [int]$script:cfg.autoStopIdleMinutes
      sampledAt = $script:idle.sampledAt
    }
    dsh = [ordered]@{ running = [bool]$script:probe.ok; lastAliveAt = $aliveAt }
    actions = @($script:actions.ToArray())
    lastError = $script:lastError
  }
  try {
    Set-Content -Path $trayStatusPath -Value ($body | ConvertTo-Json -Compress -Depth 5) -Encoding UTF8
  } catch {}
}

function Update-MenuState {
  if ($script:statusItem -ne $null) {
    $script:statusItem.Text = ('状态: {0} | {1}' -f (Get-PhaseLabel $script:wd.phase), (Format-Idle))
  }
  if ($script:miAutoStart -ne $null) { $script:miAutoStart.Checked = [bool]$script:cfg.autoStart }
  if ($script:miAutoStopExit -ne $null) { $script:miAutoStopExit.Checked = [bool]$script:cfg.autoStopOnExit }
  if ($script:miWatchdog -ne $null) { $script:miWatchdog.Checked = [bool]$script:cfg.watchdogEnabled }
  if ($script:miIdle -ne $null) {
    foreach ($entry in $script:miIdle) {
      $entry.Item.Checked = ([int]$script:cfg.autoStopIdleMinutes -eq [int]$entry.Minutes)
    }
  }
  if ($tray -ne $null) {
    $short = 'DSH Web: ' + (Get-PhaseLabel $script:wd.phase)
    try { $tray.Text = $short } catch {}
  }
}

# ---- self test (exercises the real netstat parser from stdin) ----

if ($SelfTest) {
  $text = [Console]::In.ReadToEnd()
  $lines = @()
  if ($text -ne $null -and $text -ne '') { $lines = @($text -split "\\r?\\n") }
  Read-TrayConfig
  $count = Get-IdleEstablishedCount -Port $webPort -Exclude @($script:cfg.idleProbeExcludeProcesses) -Lines $lines
  $cases = @()
  foreach ($case in @(
    @{ connections = 0; idle = 0; threshold = 30 },
    @{ connections = 0; idle = 1799; threshold = 30 },
    @{ connections = 0; idle = 1800; threshold = 30 },
    @{ connections = 1; idle = 9999; threshold = 30 },
    @{ connections = 0; idle = 9999; threshold = 0 }
  )) {
    $cases += [ordered]@{
      connections = $case.connections
      idleSeconds = $case.idle
      thresholdMinutes = $case.threshold
      due = (Test-IdleStopDue -Connections $case.connections -IdleSeconds $case.idle -ThresholdMinutes $case.threshold)
    }
  }
  Write-Output ([ordered]@{
    port = $webPort
    connections = $count
    excludes = @($script:cfg.idleProbeExcludeProcesses)
    idleCases = $cases
  } | ConvertTo-Json -Compress -Depth 5)
  return
}

if ($Regenerate) {
  New-DshShortcut
  Write-Output (Join-Path ([Environment]::GetFolderPath('Desktop')) ($shortcutName + '.lnk'))
  return
}

# ---- tray ----

$mutex = New-Object System.Threading.Mutex($false, '${mutexName()}')
try {
  if (-not $mutex.WaitOne(0, $false)) {
    # Second double-click while the tray is already up: open the web page.
    Open-DshPage
    return
  }
} catch {
  return
}

$tray = New-Object System.Windows.Forms.NotifyIcon
try {
  $tray.Icon = New-Object System.Drawing.Icon($iconPath)
} catch {
  $tray.Icon = [System.Drawing.SystemIcons]::Application
}
$tray.Text = $shortcutName
$tray.Visible = $true
$tray.Add_DoubleClick({ Open-DshPage })

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$script:statusItem = $menu.Items.Add('状态: 启动中')
$script:statusItem.Enabled = $false
$menu.Items.Add((New-Object System.Windows.Forms.ToolStripSeparator))

$openItem = $menu.Items.Add('打开 DSH 网页')
$openItem.Add_Click({ Open-DshPage })
$startItem = $menu.Items.Add('启动 DSH 服务')
$startItem.Add_Click({
  Start-DshWsl
  Add-TrayAction 'start' $true 'requested from the tray menu'
  $script:wd.stoppedIntentionally = $false
  $script:wd.autoPaused = $false
  $script:wd.probeFailures = 0
  $script:wd.restartFailures = 0
  $script:wd.phase = 'starting'
  $script:wd.restartDeadline = (Get-Date).AddSeconds($script:cfg.restartWaitSec)
  Write-TrayLog 'INFO' 'DSH start requested from the tray menu'
  Update-MenuState
})
$stopItem = $menu.Items.Add('停止 DSH 服务')
$stopItem.Add_Click({
  Stop-Dsh
  Add-TrayAction 'stop' $true 'requested from the tray menu'
  $script:wd.stoppedIntentionally = $true
  $script:wd.phase = 'stopped'
  $script:wd.probeFailures = 0
  $script:wd.restartFailures = 0
  $script:idle.idleSeconds = 0
  Write-TrayLog 'INFO' 'DSH stopped from the tray menu; the watchdog will not restart it until it answers again'
  Update-MenuState
})
$restartItem = $menu.Items.Add('重启 DSH 服务')
$restartItem.Add_Click({
  $script:wd.restartFailures = 0
  $script:wd.autoPaused = $false
  $script:wd.stoppedIntentionally = $false
  Write-TrayLog 'INFO' 'manual restart requested from the tray menu'
  Restart-Dsh
  Add-TrayAction 'restart' $true 'requested from the tray menu'
  $script:wd.lastRestartAt = Get-Date
  $script:wd.lastRestartOk = $null
  $script:wd.restartDeadline = (Get-Date).AddSeconds($script:cfg.restartWaitSec)
  $script:wd.phase = 'restarting'
  Update-MenuState
})
$recreateItem = $menu.Items.Add('重新生成桌面快捷方式')
$recreateItem.Add_Click({ New-DshShortcut })
$menu.Items.Add((New-Object System.Windows.Forms.ToolStripSeparator))

$script:miAutoStart = $menu.Items.Add('托盘启动时自动启动 DSH')
$script:miAutoStart.CheckOnClick = $true
$script:miAutoStart.Add_Click({
  $script:cfg.autoStart = [bool]$script:miAutoStart.Checked
  Save-TrayConfig
  Add-TrayAction 'toggle' $true ('autoStart={0}' -f $script:cfg.autoStart)
  Write-TrayLog 'INFO' ('switch changed: autoStart={0}' -f $script:cfg.autoStart)
  Update-MenuState
})

$script:miAutoStopExit = $menu.Items.Add('退出托盘时停止 DSH')
$script:miAutoStopExit.CheckOnClick = $true
$script:miAutoStopExit.Add_Click({
  $script:cfg.autoStopOnExit = [bool]$script:miAutoStopExit.Checked
  Save-TrayConfig
  Add-TrayAction 'toggle' $true ('autoStopOnExit={0}' -f $script:cfg.autoStopOnExit)
  Write-TrayLog 'INFO' ('switch changed: autoStopOnExit={0}' -f $script:cfg.autoStopOnExit)
  Update-MenuState
})

$script:miWatchdog = $menu.Items.Add('守护进程（自动重启）')
$script:miWatchdog.CheckOnClick = $true
$script:miWatchdog.Add_Click({
  $script:cfg.watchdogEnabled = [bool]$script:miWatchdog.Checked
  Save-TrayConfig
  Add-TrayAction 'toggle' $true ('watchdogEnabled={0}' -f $script:cfg.watchdogEnabled)
  Write-TrayLog 'INFO' ('switch changed: watchdogEnabled={0}' -f $script:cfg.watchdogEnabled)
  Update-MenuState
})

$idleItem = $menu.Items.Add('空闲自动停止')
$idleMenu = New-Object System.Windows.Forms.ToolStripDropDownMenu
$script:miIdle = @()
foreach ($minutes in @(0, 5, 15, 30, 60)) {
  $entry = New-Object System.Windows.Forms.ToolStripMenuItem
  $entry.Text = if ($minutes -eq 0) { '关闭' } else { ('{0} 分钟无连接' -f $minutes) }
  $entry.Tag = $minutes
  $entry.CheckOnClick = $false
  $entry.Add_Click({
    $script:cfg.autoStopIdleMinutes = [int]$this.Tag
    $script:idle.idleSeconds = 0
    Save-TrayConfig
    Add-TrayAction 'toggle' $true ('autoStopIdleMinutes={0}' -f $script:cfg.autoStopIdleMinutes)
    Write-TrayLog 'INFO' ('switch changed: autoStopIdleMinutes={0}' -f $script:cfg.autoStopIdleMinutes)
    Update-MenuState
  }.GetNewClosure())
  $script:miIdle += [pscustomobject]@{ Item = $entry; Minutes = $minutes }
  [void]$idleMenu.Items.Add($entry)
}
$idleItem.DropDown = $idleMenu
$menu.Items.Add((New-Object System.Windows.Forms.ToolStripSeparator))

$exitItem = $menu.Items.Add('退出')
$exitItem.Add_Click({
  if ([bool]$script:cfg.autoStopOnExit) {
    Write-TrayLog 'INFO' 'tray exiting; stopping DSH (autoStopOnExit)'
    Add-TrayAction 'stop' $true 'tray exit (autoStopOnExit)'
    Stop-Dsh
  } else {
    Write-TrayLog 'INFO' 'tray exiting; autoStopOnExit is off, DSH keeps running'
  }
  Write-TrayLog 'INFO' 'tray exiting; watchdog stopped'
  $tray.Visible = $false
  $tray.Dispose()
  [System.Windows.Forms.Application]::Exit()
})
$tray.ContextMenuStrip = $menu

# ---- initial actions ----

Read-TrayConfig
Write-TrayLog 'INFO' ('tray started (config={0}, autoStart={1}, autoStopOnExit={2}, autoStopIdleMinutes={3}, watchdog={4}, probe every {5}s)' -f $script:cfgSource, $script:cfg.autoStart, $script:cfg.autoStopOnExit, $script:cfg.autoStopIdleMinutes, $script:cfg.watchdogEnabled, $script:cfg.probeIntervalSec)
Update-MenuState

if ([bool]$script:cfg.autoStart) {
  Start-DshWsl
  $script:startedByTray = $true
  $script:wd.phase = 'starting'
  $script:wd.restartDeadline = (Get-Date).AddSeconds($script:cfg.restartWaitSec)
  $script:readyDeadline = (Get-Date).AddSeconds(30)
  Add-TrayAction 'start' $true 'tray start (autoStart)'
} else {
  # Nothing was started on purpose, so a down DSH is not a failure to repair.
  $script:wd.phase = 'starting'
  $script:wd.stoppedIntentionally = $true
  Write-TrayLog 'INFO' 'autoStart is off; DSH was not started by the tray'
}
Write-TrayStatus

$timer = New-Object System.Windows.Forms.Timer
$timer.Interval = [int]$script:cfg.probeIntervalSec * 1000
$timer.Add_Tick({
  try {
    Read-TrayConfig
    $wanted = [int]$script:cfg.probeIntervalSec * 1000
    if ($timer.Interval -ne $wanted) { $timer.Interval = $wanted }
    Update-Watchdog
    Update-Idle
    Write-TrayStatus
  } catch {
    $script:lastError = $_.Exception.Message
    Write-TrayLog 'ERROR' ('tray tick failed: {0}' -f $_.Exception.Message)
  }
  Update-MenuState
})
$timer.Start()

# Open the page once DSH answers - only when the tray started it, so restarting
# the tray does not spawn tabs for a DSH the user launched themselves.
$readyTimer = New-Object System.Windows.Forms.Timer
$readyTimer.Interval = 2000
$readyTimer.Add_Tick({
  if (-not $script:startedByTray) { $readyTimer.Stop(); return }
  try {
    $response = Invoke-WebRequest -Uri $webUrl -UseBasicParsing -TimeoutSec 2
    if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 300) {
      $auth = Get-WebAuthUrl
      if ($auth -ne $null) {
        Start-Process $auth
        $readyTimer.Stop()
        Add-TrayAction 'open' $true 'token URL'
      } elseif ((Get-Date) -gt $script:readyDeadline) {
        Start-Process $webUrl
        $readyTimer.Stop()
        Add-TrayAction 'open' $true 'plain URL (no token found)'
      }
    }
  } catch {}
})
if ($script:startedByTray) { $readyTimer.Start() }

[System.Windows.Forms.Application]::Run()

try {
  $readyTimer.Stop()
  $timer.Stop()
} catch {}
try {
  $tray.Visible = $false
  $tray.Dispose()
} catch {}
try {
  $mutex.ReleaseMutex()
} catch {}
`;
}
