/**
 * Generated artifact text: the WSL-side launcher/stop scripts and the hidden
 * Windows launcher. The tray helper itself lives in tray-script.ts; the names
 * and launch facts are re-exported from names.ts so existing importers keep
 * working.
 */

export * from './names.ts'
export { buildTrayScript, wslLogUncPath } from './tray-script.ts'
export { DEFAULT_TRAY_CONFIG, TRAY_CONFIG_NAME, type TrayConfig } from './config.ts'

import { PLUGIN_ID, TRAY_SCRIPT_NAME, WSL_DIR_NAME } from './names.ts'

/**
 * Build the WSL-side launcher. It starts the same DSH web CLI the running
 * plugin host came from, waits for readiness, and opens the default browser.
 *
 * Source checkouts are launched through their BUILD OUTPUT only. Running one
 * from `src` (tsx) puts a src instance and a lib instance of the same packages
 * in one process — plugin packages resolve through the runtime mode, which
 * loads lib — and symbols never cross instances, so tool calls fail with
 * undefined state. When a project path is configured explicitly, a missing
 * build output is a hard error rather than a silent fallback to another
 * install the user did not ask for.
 *
 * @param params - launch facts resolved from the running host.
 */
export function buildStartScript(params: {
  nodeBin: string
  sourceCli: string | null
  sourceCwd: string | null
  bakedCli: string | null
  webUrl: string
  /** True when the project path was set by the user (not auto-detected). */
  sourceConfigured?: boolean
}): string {
  const logFile = `"$HOME/.dsh/${WSL_DIR_NAME}/start.log"`
  const sourceCli = params.sourceCli === null ? '' : JSON.stringify(params.sourceCli)
  const sourceCwd = params.sourceCwd === null ? '' : JSON.stringify(params.sourceCwd)
  const bakedCli = params.bakedCli === null ? '' : JSON.stringify(params.bakedCli)
  const sourceConfigured = params.sourceConfigured === true ? '1' : '0'
  return `#!/usr/bin/env bash
# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
set -u

URL=${JSON.stringify(params.webUrl)}
LOG_FILE=${logFile}
PID_FILE="$HOME/.dsh/${WSL_DIR_NAME}/dsh.pid"
NODE=${JSON.stringify(params.nodeBin)}
SOURCE_CLI=${sourceCli}
SOURCE_CWD=${sourceCwd}
SOURCE_CONFIGURED=${sourceConfigured}
BAKED_CLI=${bakedCli}

# Forward machine-local secrets to the launched DSH (e.g. GITHUB_TOKEN for
# the GitHub MCP server). Keep one KEY=VALUE per line; chmod 600.
if [ -f "$HOME/.dsh/github-mcp-token" ]; then
  set -a
  . "$HOME/.dsh/github-mcp-token"
  set +a
fi

# Liveness probe with a dependency chain: curl, then wget, then bash's own
# /dev/tcp so a minimal distro without downloaders still detects a live DSH.
is_ready() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsS -o /dev/null --max-time 2 "$URL" 2>/dev/null
  elif command -v wget >/dev/null 2>&1; then
    wget -q -T 2 -O /dev/null "$URL" 2>/dev/null
  else
    local host port
    host=\${URL#http://}; host=\${host%%/*}
    port=\${host##*:}; host=\${host%%:*}
    (exec 3<>"/dev/tcp/$host/$port") 2>/dev/null
  fi
}

mkdir -p "$(dirname "$LOG_FILE")"

log() {
  printf '%s %s\\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >>"$LOG_FILE"
}

if is_ready; then
  exit 0
fi

# A source checkout is always launched through its BUILD OUTPUT
# (apps/cli/lib/bin.js). Launching one from src mixes a src instance and a lib
# instance of the same packages in one process — plugin packages resolve
# through the runtime resolution mode, which loads lib — and symbols never
# cross instances, so tool state comes back undefined and tool calls fail.
# This script therefore never launches src.
source_build_ready() {
  [ -n "$SOURCE_CLI" ] && [ -f "$SOURCE_CLI" ]
}

# Best-effort freshness check: the cli sources only. A stale build output runs
# old code, which looks exactly like a code change that did nothing.
source_build_stale() {
  local src_dir newer
  [ -n "$SOURCE_CLI" ] || return 1
  src_dir="$(dirname "$(dirname "$SOURCE_CLI")")/src"
  [ -d "$src_dir" ] || return 1
  newer="$(find "$src_dir" -name '*.ts' -newer "$SOURCE_CLI" -print -quit 2>/dev/null)"
  [ -n "$newer" ]
}

# Opt-in: build a checkout whose output is missing. A full build is slow, so it
# only runs when the caller exported DSH_WEB_TRAY_AUTO_BUILD=1.
auto_build_source() {
  local cwd="\${SOURCE_CWD:-}"
  [ "\${DSH_WEB_TRAY_AUTO_BUILD:-0}" = "1" ] || return 1
  [ -n "$cwd" ] && [ -d "$cwd" ] || return 1
  command -v pnpm >/dev/null 2>&1 || return 1
  log "source build output missing; running 'pnpm run build' in $cwd"
  (cd "$cwd" && pnpm run build) >>"$LOG_FILE" 2>&1
}

# Run the checkout's build output in the FOREGROUND of the hidden wsl.exe
# session so WSL keeps the distro alive and this PID tracks the final process.
start_from_source_build() {
  if source_build_stale; then
    log "WARN cli sources are newer than the build output; run 'pnpm run build' to refresh $SOURCE_CLI"
  fi
  if [ -n "$SOURCE_CWD" ] && [ -d "$SOURCE_CWD" ]; then
    cd "$SOURCE_CWD" 2>/dev/null || true
  fi
  log "launching DSH from the source build output: $SOURCE_CLI"
  exec "$NODE" "$SOURCE_CLI" web --no-open >>"$LOG_FILE" 2>&1
}

# Launch DSH hidden and in the foreground. Try the most reliable launcher
# first, then the baked-in current CLI, then npx, so npm / npx installs all
# work; a configured source checkout takes precedence over all of them.
launch_dsh() {
  # exec keeps the shell PID, so this file tracks the final DSH process and
  # stop.sh can stop exactly the instance this script launched.
  echo $$ > "$PID_FILE"

  # An explicitly configured project path means "run this checkout": only its
  # build output is acceptable — never src (see above), and never whichever
  # dsh happens to be on PATH, which may be a different version entirely.
  if [ "$SOURCE_CONFIGURED" = "1" ]; then
    if ! source_build_ready; then
      auto_build_source || true
    fi
    if source_build_ready; then
      start_from_source_build
    fi
    log "ERROR source build output is missing: $SOURCE_CLI"
    log "ERROR build the checkout before launching it: cd \${SOURCE_CWD:-CHECKOUT_ROOT} && pnpm run build"
    exit 1
  fi

  if command -v dsh >/dev/null 2>&1; then
    exec dsh web --no-open >>"$LOG_FILE" 2>&1
  fi

  if source_build_ready; then
    start_from_source_build
  fi

  if [ -n "$BAKED_CLI" ] && [ -x "$BAKED_CLI" ]; then
    exec "$NODE" "$BAKED_CLI" web --no-open >>"$LOG_FILE" 2>&1
  fi

  if command -v npx >/dev/null 2>&1; then
    exec npx --yes dsh web --no-open >>"$LOG_FILE" 2>&1
  fi

  log "ERROR no usable DSH launcher found (no dsh on PATH, no source build output, no npx)"
  echo "No usable DSH launcher found. Check $LOG_FILE" >&2
  exit 1
}

launch_dsh
`
}

/**
 * Build the WSL-side stop script. The tray runs it through `wsl.exe`; it
 * stops exactly the instance start.sh launched (PID file, written before
 * exec so it tracks the final DSH process), then falls back to a pkill whose
 * bracketed patterns cover every launcher flavor (source build output, npm
 * global, npx all end in `bin.js web`) without matching the wsl.exe/bash
 * wrapper that carries the pattern text in its own command line. A dev
 * instance started from source (`node --import tsx/esm .../src/bin.ts web`) is
 * covered by a second pattern, because "restart DSH" must also replace one.
 */
export function buildStopScript(): string {
  return `#!/usr/bin/env bash
# Generated by ${PLUGIN_ID}. Do not edit by hand; regenerate from the DSH plugin card.
set -u

PID_FILE="$HOME/.dsh/${WSL_DIR_NAME}/dsh.pid"

if [ -r "$PID_FILE" ]; then
  pid="$(cat "$PID_FILE" 2>/dev/null || true)"
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    kill "$pid" 2>/dev/null || true
  fi
  rm -f "$PID_FILE"
fi

pkill -f '[b]in\\.js web' 2>/dev/null || true
pkill -f '[s]rc/bin\\.ts web' 2>/dev/null || true
exit 0
`
}

/**
 * Build the Windows-side hidden launcher for the tray helper. The shortcut
 * points at wscript.exe (a GUI-subsystem host, no console) and passes this
 * script; the script derives the PowerShell path from its own location and
 * starts the tray helper with window style 0.
 */
export function buildTrayVbs(): string {
  return `' Generated by ${PLUGIN_ID}. Do not edit by hand.
Set fso = CreateObject("Scripting.FileSystemObject")
dir = fso.GetParentFolderName(WScript.ScriptFullName)
Set sh = CreateObject("WScript.Shell")
sh.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & dir & "\\${TRAY_SCRIPT_NAME}""", 0, False
`
}